import { useEffect, useState } from 'react'
import { createClinicalAlertRuleChangeRequest, getClinicalAlertRules, transitionClinicalAlertRuleChangeRequest, type ClinicalAlertRuleChangeRequestDetail, type ClinicalAlertRuleItem } from '../../api.ts'
import { showToast } from '../../components/Toast.tsx'

export default function AlertRuleGovernance({ sessionId }: { sessionId: string }) {
  const [rules, setRules] = useState<ClinicalAlertRuleItem[]>([])
  const [draft, setDraft] = useState<ClinicalAlertRuleItem | null>(null)
  const [reason, setReason] = useState('')
  const [request, setRequest] = useState<ClinicalAlertRuleChangeRequestDetail | null>(null)
  const [busy, setBusy] = useState(false)
  useEffect(() => { void getClinicalAlertRules(sessionId).then((value) => { setRules(value.rules); setDraft(value.rules[0] ?? null) }).catch(() => showToast('Could not load alert rules.', 'error')) }, [sessionId])
  const propose = async () => { if (!draft || !reason.trim()) return; setBusy(true); try { setRequest(await createClinicalAlertRuleChangeRequest(sessionId, { ...draft, reason: reason.trim() })); setReason(''); showToast('Alert-rule proposal created.', 'success') } catch { showToast('Could not create the alert-rule proposal.', 'error') } finally { setBusy(false) } }
  const transition = async (action: 'submit' | 'approve' | 'reject' | 'activate' | 'cancel') => { if (!request) return; setBusy(true); try { setRequest(await transitionClinicalAlertRuleChangeRequest(sessionId, request.request.requestId, action, { expectedVersion: request.request.version, note: action === 'reject' || action === 'cancel' ? 'Governance decision' : null })); } catch { showToast('The proposal changed. Refresh and try again.', 'error') } finally { setBusy(false) } }
  const allowed = request?.request.status === 'draft' ? ['submit', 'cancel'] : request?.request.status === 'submitted' ? ['approve', 'reject', 'cancel'] : request?.request.status === 'approved' ? ['activate', 'cancel'] : []
  return <section className="cl-card"><h2 className="cl-card-title">Rules and alerts governance</h2><p className="clinician-page-subtitle">Active clinical alerts remain read-only. Prepare a complete rule definition, record why it changes, then advance its proposal.</p><div className="cl-access-grid"><section className="cl-access-panel"><h3 className="cl-access-title">Proposed rule</h3><label className="cl-admin-field"><span>Active rule baseline</span><select className="ne-input" value={draft?.key ?? ''} onChange={(event) => setDraft(rules.find((rule) => rule.key === event.target.value) ?? null)}>{rules.map((rule) => <option key={rule.key} value={rule.key}>{rule.title}</option>)}</select></label>{draft && <><label className="cl-admin-field"><span>Title</span><input className="ne-input" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label className="cl-admin-field"><span>Alert message</span><textarea className="ne-input" value={draft.message} onChange={(event) => setDraft({ ...draft, message: event.target.value })} /></label><label className="cl-admin-field"><span>Reason</span><textarea className="ne-input" value={reason} onChange={(event) => setReason(event.target.value)} required /></label><button className="cl-btn-primary" type="button" disabled={busy || !reason.trim()} onClick={() => void propose()}>Create proposal</button></>}</section><section className="cl-access-panel"><h3 className="cl-access-title">Proposal state</h3>{request ? <><p><strong>{request.request.proposedDefinition.title}</strong></p><p className="cl-admin-form-copy">{request.request.status} · version {request.request.version} · {request.events.length} recorded events</p><div className="cl-access-actions">{allowed.map((action) => <button key={action} className="cl-btn-secondary" type="button" disabled={busy} onClick={() => void transition(action as 'submit' | 'approve' | 'reject' | 'activate' | 'cancel')}>{action}</button>)}</div></> : <p className="cl-empty-text">Create a proposal to begin review.</p>}</section></div></section>
}
