import { useEffect, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { getInventory, type InventoryResponse } from '../../api.ts'
import type { ClinicianOutletContext } from './ClinicianShell.tsx'

export default function InventoryWorkspace() {
  const { session } = useOutletContext<ClinicianOutletContext>()
  const [data, setData] = useState<InventoryResponse | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { getInventory(session.sessionId).then(setData).catch(() => setError('Could not load inventory.')) }, [session.sessionId])
  return <div className="clinician-page"><div className="clinician-page-header"><div><h1 className="clinician-page-title">Inventory</h1><p className="clinician-page-subtitle">Stock levels, lot pressure, and recent handling activity.</p></div>{data && <span className="health-as-of">As of {data.asOfDate}</span>}</div>{error && <div className="error-banner">{error}</div>}{!data && !error && <div className="cl-card"><div className="skeleton-list">{[0,1,2].map((i) => <div key={i} className="skeleton-row" style={{ height: 56 }} />)}</div></div>}{data && <><section className="cl-stats-grid"><div className="cl-stat-tile"><strong>{data.summary.activeItems}</strong><span>Active items</span></div><div className="cl-stat-tile"><strong>{data.summary.activeLots}</strong><span>Tracked lots</span></div><div className="cl-stat-tile"><strong>{data.summary.belowReorderPoint}</strong><span>Below reorder point</span></div><div className="cl-stat-tile"><strong>{data.summary.expiringWithin90Days}</strong><span>Expiring within 90 days</span></div></section><section className="cl-card"><div className="cl-card-header"><h2 className="cl-card-title">Stock ledger</h2></div><div className="inventory-modern-list">{data.items.map((item) => <article key={item.itemId} className={`inventory-modern-item${item.belowReorderPoint ? ' inventory-modern-low' : ''}`}><div><strong>{item.name}</strong><p>{item.itemCode} / {item.category}</p></div><div><strong>{item.quantityOnHand} {item.unit}</strong><p>Reorder at {item.reorderPoint}</p></div><div className="inventory-modern-lots">{item.lots.map((lot) => <span key={lot.lotId}>{lot.facilityCode} / {lot.lotNumber} / {lot.quantityOnHand}{lot.expirationDate ? ` / exp ${lot.expirationDate}` : ''}</span>)}</div></article>)}</div></section><section className="cl-card"><div className="cl-card-header"><h2 className="cl-card-title">Recent activity</h2></div><div className="inventory-modern-list">{data.recentTransactions.map((row) => <article key={row.transactionId} className="inventory-modern-item"><strong className={row.quantityDelta < 0 ? 'inventory-modern-out' : 'inventory-modern-in'}>{row.quantityDelta > 0 ? '+' : ''}{row.quantityDelta}</strong><div><strong>{row.itemName || row.itemCode}</strong><p>{row.transactionType} / {row.facilityCode}{row.counterpartyFacilityCode ? ` / ${row.counterpartyFacilityCode}` : ''}</p></div><p>{row.reason ?? 'No reason supplied'}</p></article>)}</div></section></>}</div>
}
