import { useEffect, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { createPatientAuthorization, getPatientAuthorizations, updatePatientAuthorizationStatus, type PatientAuthorization } from '../../api.ts'
import type { PatientOutletContext } from './PatientShell.tsx'

export default function PatientAuthorizations() {
  const { session, patientId } = useOutletContext<PatientOutletContext>()
  const [authorizations, setAuthorizations] = useState<PatientAuthorization[]>([]); const [payer, setPayer] = useState(''); const [service, setService] = useState(''); const [expiresAt, setExpiresAt] = useState(''); const [approvalNumber, setApprovalNumber] = useState<Record<string, string>>({}); const [error, setError] = useState('')
  const load = () => getPatientAuthorizations(session.sessionId, patientId).then(setAuthorizations).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load authorizations.'))
  useEffect(() => { load() }, [patientId]) // eslint-disable-line react-hooks/exhaustive-deps
  async function create() { if (!payer.trim() || !service.trim()) return; try { await createPatientAuthorization(session.sessionId, patientId, { payer, service, expiresAt: expiresAt || undefined }); setPayer(''); setService(''); setExpiresAt(''); setError(''); load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create authorization.') } }
  async function transition(id: string, status: 'submitted' | 'approved' | 'denied' | 'expired' | 'cancelled') { try { await updatePatientAuthorizationStatus(session.sessionId, patientId, id, status, status === 'approved' ? approvalNumber[id] : undefined); setError(''); load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update authorization.') } }
  return <div className="clinician-page"><div className="clinician-page-header"><h1 className="clinician-page-title">Authorizations</h1><p className="clinician-page-subtitle">Document local payer-authorization status; no payer submission or eligibility verification is performed.</p></div><section className="cl-card"><div className="cl-inline-form"><label className="cl-admin-field"><span>Payer</span><input className="ne-input" value={payer} onChange={(event) => setPayer(event.target.value)} /></label><label className="cl-admin-field"><span>Service</span><input className="ne-input" value={service} onChange={(event) => setService(event.target.value)} /></label><label className="cl-admin-field"><span>Expiry</span><input className="ne-input" type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label><div className="cl-inline-form-actions"><button className="cl-btn-primary" type="button" onClick={create}>Create draft</button></div></div>{error && <p className="cl-error-text">{error}</p>}</section><section className="cl-card"><table className="cl-table"><thead><tr><th>Payer</th><th>Service</th><th>Status</th><th>Expiry</th><th /></tr></thead><tbody>{authorizations.map((item) => <tr key={item.id}><td>{item.payer}</td><td>{item.service}</td><td>{item.status}</td><td>{item.expiresAt ? new Date(item.expiresAt).toLocaleDateString() : '—'}</td><td>{item.status === 'draft' && <><button className="cl-btn-secondary" type="button" onClick={() => transition(item.id, 'submitted')}>Submit</button> <button className="cl-btn-secondary" type="button" onClick={() => transition(item.id, 'cancelled')}>Cancel</button></>}{item.status === 'submitted' && <><input className="ne-input" placeholder="Approval #" value={approvalNumber[item.id] || ''} onChange={(event) => setApprovalNumber({ ...approvalNumber, [item.id]: event.target.value })} /><button className="cl-btn-secondary" type="button" onClick={() => transition(item.id, 'approved')}>Approve</button> <button className="cl-btn-secondary" type="button" onClick={() => transition(item.id, 'denied')}>Deny</button></>}{item.status === 'approved' && <button className="cl-btn-secondary" type="button" onClick={() => transition(item.id, 'expired')}>Expire</button>}</td></tr>)}</tbody></table>{authorizations.length === 0 && <p className="cl-empty-text">No authorizations have been recorded.</p>}</section></div>
}
