import { useEffect, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { addTherapyGroupMember, createTherapyGroup, getTherapyGroupMembers, getTherapyGroups, type TherapyGroup, type TherapyGroupMember } from '../../api.ts'
import type { ClinicianOutletContext } from './ClinicianShell.tsx'

export default function TherapyGroups() {
  const { session } = useOutletContext<ClinicianOutletContext>()
  const [groups, setGroups] = useState<TherapyGroup[]>([]); const [name, setName] = useState(''); const [capacity, setCapacity] = useState(12); const [selectedGroup, setSelectedGroup] = useState<TherapyGroup | null>(null); const [members, setMembers] = useState<TherapyGroupMember[]>([]); const [patientId, setPatientId] = useState(''); const [error, setError] = useState('')
  const load = () => getTherapyGroups(session.sessionId).then((data) => setGroups(data.groups)).catch(() => {})
  useEffect(() => { load() }, [])
  async function create() { if (!name.trim()) return; await createTherapyGroup(session.sessionId, { name, capacity }); setName(''); load() }
  async function select(group: TherapyGroup) { setSelectedGroup(group); setError(''); setMembers(await getTherapyGroupMembers(session.sessionId, group.id)) }
  async function addMember() { if (!selectedGroup || !patientId.trim()) return; try { await addTherapyGroupMember(session.sessionId, selectedGroup.id, patientId); setPatientId(''); setMembers(await getTherapyGroupMembers(session.sessionId, selectedGroup.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to add member.') } }
  return <div className="clinician-page"><div className="clinician-page-header"><h1 className="clinician-page-title">Therapy groups</h1><p className="clinician-page-subtitle">Create group programs, assign known patients, and then schedule group sessions.</p></div><section className="cl-card"><div className="cl-inline-form"><label className="cl-admin-field"><span>Group name</span><input className="ne-input" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="cl-admin-field"><span>Capacity</span><input className="ne-input" type="number" min="1" max="200" value={capacity} onChange={(event) => setCapacity(Number(event.target.value))} /></label><div className="cl-inline-form-actions"><button className="cl-btn-primary" type="button" onClick={create}>Create group</button></div></div></section><section className="cl-card"><table className="cl-table"><thead><tr><th>Group</th><th>Status</th><th>Capacity</th><th /></tr></thead><tbody>{groups.map((group) => <tr key={group.id}><td>{group.name}</td><td>{group.status}</td><td>{group.capacity}</td><td><button className="cl-btn-secondary" type="button" onClick={() => select(group)}>Members</button></td></tr>)}</tbody></table>{groups.length === 0 && <p className="cl-empty-text">No therapy groups are defined.</p>}</section>{selectedGroup && <section className="cl-card"><h2 className="cl-card-title">{selectedGroup.name} members</h2><div className="cl-inline-form"><label className="cl-admin-field"><span>Patient ID or public ID</span><input className="ne-input" value={patientId} onChange={(event) => setPatientId(event.target.value)} /></label><div className="cl-inline-form-actions"><button className="cl-btn-primary" type="button" onClick={addMember}>Add member</button></div></div>{error && <p className="cl-error-text">{error}</p>}<table className="cl-table"><thead><tr><th>Patient</th><th>Legacy ID</th><th>Joined</th></tr></thead><tbody>{members.map((member) => <tr key={member.patientId}><td>{member.displayName}</td><td>{member.legacyPid}</td><td>{new Date(member.joinedAt).toLocaleDateString()}</td></tr>)}</tbody></table>{members.length === 0 && <p className="cl-empty-text">No members have been assigned.</p>}</section>}</div>
}
