// SPDX-FileCopyrightText: 2026 Neil Kimber and AvenChart contributors
// SPDX-License-Identifier: GPL-3.0-or-later

import { useCallback, useEffect, useId, useRef, useState } from 'react'
import { isRequestCancellation } from '../../api/transport.ts'
import { finalizeTelehealthEncounter, getTelehealthFinalClinicalReview, type TelehealthFinalClinicalReviewWorkspace } from './api.ts'

type Props = { consultationId: string; onFinalized?: () => void }

export default function TelehealthEncounterFinalizationPanel({ consultationId, onFinalized }: Props) {
  const headingId = useId(); const errorRef = useRef<HTMLParagraphElement>(null)
  const [workspace, setWorkspace] = useState<TelehealthFinalClinicalReviewWorkspace | null>(null)
  const [sourceConfirmed, setSourceConfirmed] = useState(false); const [syntheticConfirmed, setSyntheticConfirmed] = useState(false)
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState<string | null>(null)
  useEffect(() => { if (error) errorRef.current?.focus() }, [error])
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(null); try { const result = await getTelehealthFinalClinicalReview(consultationId, signal); setWorkspace(result); setStatus(result.currentReview ? 'Current review evidence is available for synthetic encounter locking.' : 'A current final clinical-review record is required before synthetic encounter locking.') } catch (caught) { if (!isRequestCancellation(caught)) setError(caught instanceof Error ? caught.message : 'Finalization requirements could not be loaded.') } finally { setLoading(false) } }, [consultationId])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load])
  const ready = Boolean(workspace?.reviewEnabled && workspace.currentReview && sourceConfirmed && syntheticConfirmed)
  async function finalize() { if (!workspace?.currentReview || !workspace.safetyDisposition || !ready || saving) return; setSaving(true); setError(null); try { const result = await finalizeTelehealthEncounter(consultationId, { expectedDocumentationVersion: workspace.documentation.version, expectedDispositionVersion: workspace.safetyDisposition.version, expectedFinalClinicalReviewVersion: workspace.currentReview.version, sourceReviewConfirmed: true, syntheticOnlyConfirmed: true }); setStatus(`Synthetic encounter lock ${result.encounterSignatureId} was recorded. No completion, delivery, billing, or claim was created.`); onFinalized?.() } catch (caught) { setError(caught instanceof Error ? caught.message : 'The synthetic encounter lock could not be recorded.'); setStatus('No completion, delivery, billing, claim, or external action occurred.') } finally { setSaving(false) } }
  return <section className="telehealth-completion-review" aria-labelledby={headingId} aria-busy={loading}><div className="telehealth-heading"><div><p className="telehealth-kicker">Synthetic encounter finalization</p><h4 id={headingId}>Lock the current encounter</h4></div><button className="telehealth-button telehealth-button-secondary" type="button" disabled={loading || saving} onClick={() => void load()}>{loading ? 'Refreshing…' : 'Reload requirements'}</button></div><p role="note">This creates the governed encounter lock in the non-production environment. It is not a legal signature, visit completion, bill, claim, patient delivery, or external action.</p>{status ? <p role="status">{status}</p> : null}{error ? <p ref={errorRef} tabIndex={-1} className="telehealth-error" role="alert">{error}</p> : null}{workspace ? <><fieldset disabled={!workspace.reviewEnabled || !workspace.currentReview || saving}><legend>Required confirmations</legend><label className="telehealth-check"><input type="checkbox" checked={sourceConfirmed} onChange={(event) => setSourceConfirmed(event.target.checked)} />I reviewed the exact current SOAP, safety-disposition, and final clinical-review versions.</label><label className="telehealth-check"><input type="checkbox" checked={syntheticConfirmed} onChange={(event) => setSyntheticConfirmed(event.target.checked)} />I confirm this is synthetic-only and has no legal, billing, or claim effect.</label></fieldset><button className="telehealth-button" type="button" disabled={!ready || saving} onClick={() => void finalize()}>{saving ? 'Locking encounter…' : 'Record synthetic encounter lock'}</button></> : null}</section>
}
