# SPDX-FileCopyrightText: 2026 Neil Kimber and AvenChart contributors
# SPDX-License-Identifier: GPL-3.0-or-later

@AvenChart.Api_HostAddress = http://localhost:5001

GET {{AvenChart.Api_HostAddress}}/health
Accept: application/json

###

GET {{AvenChart.Api_HostAddress}}/api/patients?search=MOD-PAT-0001&limit=5
Accept: application/json

###

GET {{AvenChart.Api_HostAddress}}/api/patients/MOD-PAT-0001
Accept: application/json

###
