insert into clinical_form_definitions (definition_id, stable_key, latest_revision, effective_revision, created_at, created_by, updated_at, updated_by)
values ('90f00000-0000-4000-8000-000000000006', 'legacy.clinicalnotes', 1, null, now(), 'legacy-adoption-seed', now(), 'legacy-adoption-seed')
on conflict (stable_key) do nothing;

insert into clinical_form_revisions (definition_id, revision, status, version, schema_json, renderer_version, schema_hash, author, reviewed_by, approved_by, effective_from, predecessor_revision, created_at, updated_at, updated_by)
select d.definition_id, 1, 'effective', 3,
'{"stableKey":"legacy.clinicalnotes","name":"Clinical Notes","purpose":"Legacy Clinical Notes compatibility capture for bounded encounter note entries.","contextScope":"encounter","owningService":"clinical_operations","capability":"encounters.auth_a","signaturePolicy":"author-only","sections":[{"key":"clinical_notes","title":"Clinical Notes","sequence":10,"description":"Mapped from the legacy Clinical Notes encounter form."}],"fields":[{"key":"items","sectionKey":"clinical_notes","label":"Clinical note entries","type":"repeat","sequence":10,"required":false,"accessibilityLabel":"Clinical note entries","helpText":"Each entry maps a legacy Clinical Notes row. The local form permits up to 20 entries.","maxLength":null,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":0,"repeatMaximum":20,"children":[{"key":"note_date","sectionKey":"","label":"Date","type":"date","sequence":10,"required":false,"accessibilityLabel":"Date","helpText":null,"maxLength":null,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false},{"key":"code","sectionKey":"","label":"Code","type":"text","sequence":20,"required":false,"accessibilityLabel":"Code","helpText":null,"maxLength":240,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false},{"key":"code_text","sectionKey":"","label":"Code text","type":"text","sequence":30,"required":false,"accessibilityLabel":"Code text","helpText":null,"maxLength":240,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false},{"key":"note_type","sectionKey":"","label":"Type","type":"text","sequence":40,"required":false,"accessibilityLabel":"Type","helpText":null,"maxLength":100,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false},{"key":"note_category","sectionKey":"","label":"Category","type":"text","sequence":50,"required":false,"accessibilityLabel":"Category","helpText":null,"maxLength":100,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false},{"key":"narrative","sectionKey":"","label":"Narrative","type":"multiline","sequence":60,"required":false,"accessibilityLabel":"Narrative","helpText":null,"maxLength":4000,"minimum":null,"maximum":null,"precision":null,"unit":null,"codeSystem":null,"options":[],"repeatMinimum":null,"repeatMaximum":null,"children":[],"readOnly":false}],"readOnly":false}],"rules":[]}'::jsonb,
'local-clinical-form-renderer-v1','3dee3d5d24d1e564b14e3e3e0f6c1a618895ffe2cff8cfef8431eec32066299f','legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed'
from clinical_form_definitions d where d.stable_key='legacy.clinicalnotes'
on conflict (definition_id, revision) do nothing;

update clinical_form_definitions d set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where d.stable_key='legacy.clinicalnotes' and d.effective_revision is null and exists (select 1 from clinical_form_revisions r where r.definition_id=d.definition_id and r.revision=1 and r.status='effective');

insert into clinical_form_definition_events (definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash)
select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Clinical Notes rows as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.clinicalnotes' and not exists (select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
