insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by) values('90f00000-0000-4000-8000-000000000011','legacy.transfersummary',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed') on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.transfersummary','name','Transfer Summary','purpose','Legacy Transfer Summary compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','transfer','title','Transfer Summary','sequence',10,'description','Mapped from the legacy transfer summary encounter form.')),'fields',jsonb_build_array(
jsonb_build_object('key','transfer_to','sectionKey','transfer','label','Transfer to','type','text','sequence',10,'required',false,'accessibilityLabel','Transfer to','helpText',null,'maxLength',255,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','transfer_date','sectionKey','transfer','label','Transfer date','type','date','sequence',20,'required',false,'accessibilityLabel','Transfer date','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','status_of_admission','sectionKey','transfer','label','Status of admission','type','multiline','sequence',30,'required',false,'accessibilityLabel','Status of admission','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','diagnosis','sectionKey','transfer','label','Diagnosis','type','multiline','sequence',40,'required',false,'accessibilityLabel','Diagnosis','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','intervention_provided','sectionKey','transfer','label','Intervention provided','type','multiline','sequence',50,'required',false,'accessibilityLabel','Intervention provided','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','overall_status_of_discharge','sectionKey','transfer','label','Overall status of discharge','type','multiline','sequence',60,'required',false,'accessibilityLabel','Overall status of discharge','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.transfersummary' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.transfersummary' and effective_revision is null;
