insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000017','legacy.ankleassessment',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.ankleassessment','name','Ankle Injury Assessment','purpose','Legacy ankle evaluation injury, Ottawa-rule, and x-ray assessment compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','injury','title','Injury assessment','sequence',10,'description','Mapped from the injury, Ottawa Ankle Rules, and x-ray portions of the legacy Ankle Evaluation form.')),'fields',jsonb_build_array(
jsonb_build_object('key','ankle_date_of_injuary','sectionKey','injury','label','Date of injury','type','date','sequence',10,'required',false,'accessibilityLabel','Date of injury','helpText','Legacy field name retains its original spelling for compatibility.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_work_related','sectionKey','injury','label','Work related','type','boolean','sequence',20,'required',false,'accessibilityLabel','Work related','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_foot','sectionKey','injury','label','Foot','type','select','sequence',30,'required',false,'accessibilityLabel','Foot','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-ankle-foot-v1','options',jsonb_build_array(jsonb_build_object('code','left','display','Left'),jsonb_build_object('code','right','display','Right')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_severity_of_pain','sectionKey','injury','label','Severity of pain','type','select','sequence',40,'required',false,'accessibilityLabel','Severity of pain','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-ankle-pain-v1','options',jsonb_build_array(jsonb_build_object('code','1','display','1'),jsonb_build_object('code','2','display','2'),jsonb_build_object('code','3','display','3')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_significant_swelling','sectionKey','injury','label','Significant swelling','type','boolean','sequence',50,'required',false,'accessibilityLabel','Significant swelling','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_onset_of_swelling','sectionKey','injury','label','Onset of swelling','type','select','sequence',60,'required',false,'accessibilityLabel','Onset of swelling','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-ankle-swelling-onset-v1','options',jsonb_build_array(jsonb_build_object('code','within_minutes','display','within minutes'),jsonb_build_object('code','within_hours','display','within hours')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_how_did_injury_occur','sectionKey','injury','label','How did injury occur','type','multiline','sequence',70,'required',false,'accessibilityLabel','How did injury occur','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_ottawa_bone_tenderness','sectionKey','injury','label','Ottawa bone tenderness','type','select','sequence',80,'required',false,'accessibilityLabel','Ottawa bone tenderness','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-ottawa-bone-tenderness-v1','options',jsonb_build_array(jsonb_build_object('code','medial_malleolus','display','Medial malleolus'),jsonb_build_object('code','lateral_malleolus','display','Lateral malleolus'),jsonb_build_object('code','fifth_metatarsal_base','display','Base of fifth (5th) Metatarsal'),jsonb_build_object('code','navicular','display','At the Navicular')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_able_to_bear_weight_steps','sectionKey','injury','label','Able to bear weight four steps','type','select','sequence',90,'required',false,'accessibilityLabel','Able to bear weight four steps','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-yes-no-v1','options',jsonb_build_array(jsonb_build_object('code','yes','display','Yes'),jsonb_build_object('code','no','display','No')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_x_ray_interpretation','sectionKey','injury','label','X-ray interpretation','type','select','sequence',100,'required',false,'accessibilityLabel','X-ray interpretation','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-ankle-xray-v1','options',jsonb_build_array(jsonb_build_object('code','normal','display','Normal'),jsonb_build_object('code','avulsion_medial_malleolus','display','Avulsion medial malleolus'),jsonb_build_object('code','avulsion_lateral_malleolus','display','Avulsion lateral malleolus'),jsonb_build_object('code','fracture_fifth_metatarsal','display','Fracture, Base of fifth (5th) Metatarsal'),jsonb_build_object('code','trimalleolar','display','Trimalleolar'),jsonb_build_object('code','fracture_navicular','display','Fracture at the Navicula'),jsonb_build_object('code','fracture_medial_malleolus','display','Fracture medial malleolus'),jsonb_build_object('code','fracture_lateral_malleolus','display','Fracture lateral malleolus'),jsonb_build_object('code','other','display','Other')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_additional_x_ray_notes','sectionKey','injury','label','Additional X-ray notes','type','multiline','sequence',110,'required',false,'accessibilityLabel','Additional X-ray notes','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.ankleassessment' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.ankleassessment' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Ankle Evaluation assessment fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.ankleassessment' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
