insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000015','legacy.physicalexam',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
  select jsonb_build_object(
    'stableKey','legacy.physicalexam','name','Physical Exam','purpose','Legacy Physical Exam compatibility capture for catalog-backed observation and treatment lines.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only',
    'sections',jsonb_build_array(jsonb_build_object('key','exam','title','Physical Exam','sequence',10,'description','Mapped from the legacy physical examination line-item form.')),
    'fields',jsonb_build_array(jsonb_build_object(
      'key','items','sectionKey','exam','label','Physical exam lines','type','repeat','sequence',10,'required',false,'accessibilityLabel','Physical exam lines','helpText','Each item represents one legacy physical-exam observation or treatment line.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',0,'repeatMaximum',50,'readOnly',false,
      'children',jsonb_build_array(
        jsonb_build_object('key','line_id','sectionKey','exam','label','Exam line','type','select','sequence',10,'required',true,'accessibilityLabel','Exam line','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','local-physical-exam-lines-v1','options',jsonb_build_array(
          jsonb_build_object('code','GENWELL','display','GEN — Appearance'),jsonb_build_object('code','EYECP','display','EYE — Conjuntiva, pupils'),jsonb_build_object('code','ENTTM','display','ENT — TMs/EAMs/EE, ext nose'),jsonb_build_object('code','ENTNASAL','display','ENT — Nasal mucosa pink, septum midline'),jsonb_build_object('code','ENTORAL','display','ENT — Oral mucosa pink, throat clear'),jsonb_build_object('code','ENTNECK','display','ENT — Neck supple'),jsonb_build_object('code','ENTTHY','display','ENT — Thyroid normal'),jsonb_build_object('code','CVRRR','display','CV — RRR without MOR'),jsonb_build_object('code','CVNTOH','display','CV — No thrills or heaves'),jsonb_build_object('code','CVCP','display','CV — Cartoid pulsations nl, pedal pulses nl'),jsonb_build_object('code','CVNPE','display','CV — No peripheral edema'),jsonb_build_object('code','CHNSD','display','CHEST — No skin dimpling or breast nodules'),jsonb_build_object('code','RECTAB','display','RESP — Chest CTAB'),jsonb_build_object('code','REEFF','display','RESP — Respirator effort unlabored'),jsonb_build_object('code','GIMASS','display','GI — No masses, tenderness'),jsonb_build_object('code','GIOG','display','GI — No organomegaly'),jsonb_build_object('code','GIHERN','display','GI — No hernia'),jsonb_build_object('code','GIRECT','display','GI — Anus nl, no rectal tenderness/mass'),jsonb_build_object('code','GUTEST','display','GU — No testicular tenderness, masses'),jsonb_build_object('code','GUPROS','display','GU — Prostate w/o enlrgmt, nodules, tender'),jsonb_build_object('code','GUEG','display','GU — Nl ext genitalia, vag mucosa, cervix'),jsonb_build_object('code','GUAD','display','GU — No adnexal tenderness/masses'),jsonb_build_object('code','LYAD','display','LYMPH — No adenopathy (2 areas required)'),jsonb_build_object('code','MUSTR','display','MUSC — Strength'),jsonb_build_object('code','MUROM','display','MUSC — ROM'),jsonb_build_object('code','MUSTAB','display','MUSC — Stability'),jsonb_build_object('code','MUINSP','display','MUSC — Inspection'),jsonb_build_object('code','NEUCN2','display','NEURO — CN2-12 intact'),jsonb_build_object('code','NEUREF','display','NEURO — Reflexes normal'),jsonb_build_object('code','NEUSENS','display','NEURO — Sensory exam normal'),jsonb_build_object('code','PSYOR','display','PSYCH — Orientated x 3'),jsonb_build_object('code','PSYAFF','display','PSYCH — Affect normal'),jsonb_build_object('code','SKRASH','display','SKIN — No rash or abnormal lesions'),jsonb_build_object('code','OTHER','display','OTHER — Other'),jsonb_build_object('code','TRTLABS','display','Treatment — Labs'),jsonb_build_object('code','TRTXRAY','display','Treatment — X-ray'),jsonb_build_object('code','TRTRET','display','Treatment — Return Visit')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
        jsonb_build_object('key','wnl','sectionKey','exam','label','Within normal limits','type','boolean','sequence',20,'required',false,'accessibilityLabel','Within normal limits','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
        jsonb_build_object('key','abn','sectionKey','exam','label','Abnormal','type','boolean','sequence',30,'required',false,'accessibilityLabel','Abnormal','helpText','Legacy treatment lines do not use this value.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
        jsonb_build_object('key','diagnosis','sectionKey','exam','label','Diagnosis','type','text','sequence',40,'required',false,'accessibilityLabel','Diagnosis','helpText','Legacy diagnoses are catalog-maintained per line.','maxLength',255,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
        jsonb_build_object('key','comments','sectionKey','exam','label','Comments','type','text','sequence',50,'required',false,'accessibilityLabel','Comments','helpText',null,'maxLength',250,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)
      )
    )), 'rules','[]'::jsonb
  ) as schema_json
)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by)
select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.physicalexam' on conflict(definition_id,revision) do nothing;

update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.physicalexam' and effective_revision is null;

insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash)
select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Physical Exam line capture as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.physicalexam' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
