insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000022','legacy.bronchitiscardiacexam',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.bronchitiscardiacexam','name','Bronchitis Cardiac Examination','purpose','Legacy Bronchitis cardiac examination compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','cardiac_exam','title','Cardiac examination','sequence',10,'description','Mapped from the HEART checklist and descriptive findings portion of the legacy Bronchitis form.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_heart_pmi','sectionKey','cardiac_exam','label','Laterally displaced PMI','type','boolean','sequence',10,'required',false,'accessibilityLabel','Laterally displaced PMI','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_s3','sectionKey','cardiac_exam','label','S3','type','boolean','sequence',20,'required',false,'accessibilityLabel','S3','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_s4','sectionKey','cardiac_exam','label','S4','type','boolean','sequence',30,'required',false,'accessibilityLabel','S4','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_click','sectionKey','cardiac_exam','label','Click','type','boolean','sequence',40,'required',false,'accessibilityLabel','Cardiac click','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_rub','sectionKey','cardiac_exam','label','Rub','type','boolean','sequence',50,'required',false,'accessibilityLabel','Cardiac rub','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_murmur','sectionKey','cardiac_exam','label','Murmur','type','text','sequence',60,'required',false,'accessibilityLabel','Cardiac murmur','helpText','The legacy form initially displays none.','maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_grade','sectionKey','cardiac_exam','label','Grade','type','text','sequence',70,'required',false,'accessibilityLabel','Cardiac murmur grade','helpText','The legacy form initially displays n/a.','maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_location','sectionKey','cardiac_exam','label','Location','type','text','sequence',80,'required',false,'accessibilityLabel','Cardiac murmur location','helpText','The legacy form initially displays n/a.','maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_normal','sectionKey','cardiac_exam','label','Normal cardiac exam','type','boolean','sequence',90,'required',false,'accessibilityLabel','Normal cardiac exam','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_heart_not_examined','sectionKey','cardiac_exam','label','Cardiac exam not examined','type','boolean','sequence',100,'required',false,'accessibilityLabel','Cardiac exam not examined','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitiscardiacexam' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitiscardiacexam' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis cardiac examination fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitiscardiacexam' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
