insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000021','legacy.bronchitissinusoropharynx',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.bronchitissinusoropharynx','name','Bronchitis Sinus and Oropharynx Examination','purpose','Legacy Bronchitis sinus-tenderness and oropharynx examination compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','sinus_oropharynx_exam','title','Sinus tenderness and oropharynx examination','sequence',10,'description','Mapped from the sinus-tenderness and oropharynx checklist portion of the legacy Bronchitis form.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_no_sinus_tenderness','sectionKey','sinus_oropharynx_exam','label','No sinus tenderness','type','boolean','sequence',10,'required',false,'accessibilityLabel','No sinus tenderness','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_normal','sectionKey','sinus_oropharynx_exam','label','Normal oropharynx','type','boolean','sequence',20,'required',false,'accessibilityLabel','Normal oropharynx','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_sinus_tenderness_frontal_right','sectionKey','sinus_oropharynx_exam','label','Frontal sinus tenderness right','type','boolean','sequence',30,'required',false,'accessibilityLabel','Frontal sinus tenderness right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_sinus_tenderness_frontal_left','sectionKey','sinus_oropharynx_exam','label','Frontal sinus tenderness left','type','boolean','sequence',40,'required',false,'accessibilityLabel','Frontal sinus tenderness left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_erythema','sectionKey','sinus_oropharynx_exam','label','Oropharynx erythema','type','boolean','sequence',50,'required',false,'accessibilityLabel','Oropharynx erythema','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_exudate','sectionKey','sinus_oropharynx_exam','label','Oropharynx exudate','type','boolean','sequence',60,'required',false,'accessibilityLabel','Oropharynx exudate','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_abcess','sectionKey','sinus_oropharynx_exam','label','Oropharynx abscess','type','boolean','sequence',70,'required',false,'accessibilityLabel','Oropharynx abscess','helpText','Legacy field name retains its original spelling for compatibility.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_ulcers','sectionKey','sinus_oropharynx_exam','label','Oropharynx ulcers','type','boolean','sequence',80,'required',false,'accessibilityLabel','Oropharynx ulcers','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_sinus_tenderness_maxillary_right','sectionKey','sinus_oropharynx_exam','label','Maxillary sinus tenderness right','type','boolean','sequence',90,'required',false,'accessibilityLabel','Maxillary sinus tenderness right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_sinus_tenderness_maxillary_left','sectionKey','sinus_oropharynx_exam','label','Maxillary sinus tenderness left','type','boolean','sequence',100,'required',false,'accessibilityLabel','Maxillary sinus tenderness left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_appearance','sectionKey','sinus_oropharynx_exam','label','Oropharynx appearance','type','text','sequence',110,'required',false,'accessibilityLabel','Oropharynx appearance','helpText','The legacy form initially displays normal.','maxLength',255,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_sinus_tenderness_not_examined','sectionKey','sinus_oropharynx_exam','label','Sinus tenderness not examined','type','boolean','sequence',120,'required',false,'accessibilityLabel','Sinus tenderness not examined','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_oropharynx_not_examined','sectionKey','sinus_oropharynx_exam','label','Oropharynx not examined','type','boolean','sequence',130,'required',false,'accessibilityLabel','Oropharynx not examined','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitissinusoropharynx' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitissinusoropharynx' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis sinus-tenderness and oropharynx examination fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitissinusoropharynx' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
