insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000023','legacy.bronchitislungexam',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.bronchitislungexam','name','Bronchitis Lung Examination','purpose','Legacy Bronchitis lung examination compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','lung_exam','title','Lung examination','sequence',10,'description','Mapped from the LUNGS checklist portion of the legacy Bronchitis form.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_lungs_bs_normal','sectionKey','lung_exam','label','Breath sounds normal','type','boolean','sequence',10,'required',false,'accessibilityLabel','Breath sounds normal','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_bs_reduced','sectionKey','lung_exam','label','Breath sounds reduced','type','boolean','sequence',20,'required',false,'accessibilityLabel','Breath sounds reduced','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_bs_increased','sectionKey','lung_exam','label','Breath sounds increased','type','boolean','sequence',30,'required',false,'accessibilityLabel','Breath sounds increased','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_crackles_lll','sectionKey','lung_exam','label','Crackles LLL','type','boolean','sequence',40,'required',false,'accessibilityLabel','Crackles left lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_crackles_rll','sectionKey','lung_exam','label','Crackles RLL','type','boolean','sequence',50,'required',false,'accessibilityLabel','Crackles right lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_crackles_bll','sectionKey','lung_exam','label','Crackles bilateral','type','boolean','sequence',60,'required',false,'accessibilityLabel','Crackles bilateral','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_rubs_lll','sectionKey','lung_exam','label','Rubs LLL','type','boolean','sequence',70,'required',false,'accessibilityLabel','Rubs left lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_rubs_rll','sectionKey','lung_exam','label','Rubs RLL','type','boolean','sequence',80,'required',false,'accessibilityLabel','Rubs right lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_rubs_bll','sectionKey','lung_exam','label','Rubs bilateral','type','boolean','sequence',90,'required',false,'accessibilityLabel','Rubs bilateral','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_wheezes_lll','sectionKey','lung_exam','label','Wheezes LLL','type','boolean','sequence',100,'required',false,'accessibilityLabel','Wheezes left lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_wheezes_rll','sectionKey','lung_exam','label','Wheezes RLL','type','boolean','sequence',110,'required',false,'accessibilityLabel','Wheezes right lower lobe','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_wheezes_bll','sectionKey','lung_exam','label','Wheezes bilateral','type','boolean','sequence',120,'required',false,'accessibilityLabel','Wheezes bilateral','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_wheezes_dll','sectionKey','lung_exam','label','Wheezes diffuse','type','boolean','sequence',130,'required',false,'accessibilityLabel','Wheezes diffuse','helpText','Legacy field name retains its original spelling for compatibility.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_normal_exam','sectionKey','lung_exam','label','Normal lung exam','type','boolean','sequence',140,'required',false,'accessibilityLabel','Normal lung exam','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_lungs_not_examined','sectionKey','lung_exam','label','Lung exam not examined','type','boolean','sequence',150,'required',false,'accessibilityLabel','Lung exam not examined','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitislungexam' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitislungexam' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis lung examination fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitislungexam' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
