insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000018','legacy.anklediagnosisplan',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.anklediagnosisplan','name','Ankle Injury Diagnosis and Plan','purpose','Legacy ankle evaluation diagnosis and treatment-plan compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','diagnosis_plan','title','Diagnosis and plan','sequence',10,'description','Mapped from the diagnosis and treatment-plan portion of the legacy Ankle Evaluation form.')),'fields',jsonb_build_array(
jsonb_build_object('key','ankle_diagnosis1','sectionKey','diagnosis_plan','label','Diagnosis 1','type','select','sequence',10,'required',false,'accessibilityLabel','Diagnosis 1','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-ankle-icd9-v1','options',jsonb_build_array(jsonb_build_object('code','845_00','display','845.00 ankle sprain NOS'),jsonb_build_object('code','845_01','display','845.01 Sprain Medial (Deltoid) Lig.'),jsonb_build_object('code','845_02','display','845.02 Sprain, Calcaneal fibular'),jsonb_build_object('code','825_35','display','825.35 Fracture, Base of fifth (5th) Metatarsal'),jsonb_build_object('code','825_32','display','825.32 Fracture, of Navicular (ankle)'),jsonb_build_object('code','824_2','display','824.2 Fracture, lateral malleolus, closed'),jsonb_build_object('code','824_0','display','824.0 Fracture, medial malleolus, closed'),jsonb_build_object('code','824_6','display','824.6 Fracture, Trimalleolar, closed'),jsonb_build_object('code','add_icd_code','display','Add ICD Code')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_diagnosis2','sectionKey','diagnosis_plan','label','Diagnosis 2','type','select','sequence',20,'required',false,'accessibilityLabel','Diagnosis 2','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-ankle-icd9-v1','options',jsonb_build_array(jsonb_build_object('code','845_00','display','845.00 ankle sprain NOS'),jsonb_build_object('code','845_01','display','845.01 Sprain Medial (Deltoid) Lig.'),jsonb_build_object('code','845_02','display','845.02 Sprain, Calcaneal fibular'),jsonb_build_object('code','825_35','display','825.35 Fracture, Base of fifth (5th) Metatarsal'),jsonb_build_object('code','825_32','display','825.32 Fracture, of Navicular (ankle)'),jsonb_build_object('code','824_2','display','824.2 Fracture, lateral malleolus, closed'),jsonb_build_object('code','824_0','display','824.0 Fracture, medial malleolus, closed'),jsonb_build_object('code','824_6','display','824.6 Fracture, Trimalleolar, closed'),jsonb_build_object('code','add_icd_code','display','Add ICD Code')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_diagnosis3','sectionKey','diagnosis_plan','label','Diagnosis 3','type','select','sequence',30,'required',false,'accessibilityLabel','Diagnosis 3','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-ankle-icd9-v1','options',jsonb_build_array(jsonb_build_object('code','845_00','display','845.00 ankle sprain NOS'),jsonb_build_object('code','845_01','display','845.01 Sprain Medial (Deltoid) Lig.'),jsonb_build_object('code','845_02','display','845.02 Sprain, Calcaneal fibular'),jsonb_build_object('code','825_35','display','825.35 Fracture, Base of fifth (5th) Metatarsal'),jsonb_build_object('code','825_32','display','825.32 Fracture, of Navicular (ankle)'),jsonb_build_object('code','824_2','display','824.2 Fracture, lateral malleolus, closed'),jsonb_build_object('code','824_0','display','824.0 Fracture, medial malleolus, closed'),jsonb_build_object('code','824_6','display','824.6 Fracture, Trimalleolar, closed'),jsonb_build_object('code','add_icd_code','display','Add ICD Code')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_diagnosis4','sectionKey','diagnosis_plan','label','Diagnosis 4','type','select','sequence',40,'required',false,'accessibilityLabel','Diagnosis 4','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-ankle-icd9-v1','options',jsonb_build_array(jsonb_build_object('code','845_00','display','845.00 ankle sprain NOS'),jsonb_build_object('code','845_01','display','845.01 Sprain Medial (Deltoid) Lig.'),jsonb_build_object('code','845_02','display','845.02 Sprain, Calcaneal fibular'),jsonb_build_object('code','825_35','display','825.35 Fracture, Base of fifth (5th) Metatarsal'),jsonb_build_object('code','825_32','display','825.32 Fracture, of Navicular (ankle)'),jsonb_build_object('code','824_2','display','824.2 Fracture, lateral malleolus, closed'),jsonb_build_object('code','824_0','display','824.0 Fracture, medial malleolus, closed'),jsonb_build_object('code','824_6','display','824.6 Fracture, Trimalleolar, closed'),jsonb_build_object('code','add_icd_code','display','Add ICD Code')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_additional_diagnisis','sectionKey','diagnosis_plan','label','Additional diagnosis','type','multiline','sequence',50,'required',false,'accessibilityLabel','Additional diagnosis','helpText','Legacy field name retains its original spelling for compatibility.','maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ankle_plan','sectionKey','diagnosis_plan','label','Plan','type','multiline','sequence',60,'required',false,'accessibilityLabel','Plan','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.anklediagnosisplan' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.anklediagnosisplan' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Ankle Evaluation diagnosis and plan fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.anklediagnosisplan' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
