insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000019','legacy.bronchitishistory',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.bronchitishistory','name','Bronchitis History and Symptom Review','purpose','Legacy Bronchitis form onset, HPI, pertinent symptom, and history-review compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(
jsonb_build_object('key','illness_history','title','Illness history','sequence',10,'description','Mapped from the onset-of-illness and HPI portion of the legacy Bronchitis form.'),
jsonb_build_object('key','pertinent_symptoms','title','Other pertinent symptoms','sequence',20,'description','Mapped from the legacy Bronchitis pertinent-symptom checklist.'),
jsonb_build_object('key','history_review','title','History review','sequence',30,'description','Mapped from the legacy Bronchitis review-of-history checklist.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_date_of_illness','sectionKey','illness_history','label','Onset of illness','type','date','sequence',10,'required',false,'accessibilityLabel','Onset of illness','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_hpi','sectionKey','illness_history','label','HPI','type','multiline','sequence',20,'required',false,'accessibilityLabel','History of present illness','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_fever','sectionKey','pertinent_symptoms','label','Fever','type','boolean','sequence',10,'required',false,'accessibilityLabel','Fever','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_cough','sectionKey','pertinent_symptoms','label','Cough','type','boolean','sequence',20,'required',false,'accessibilityLabel','Cough','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_dizziness','sectionKey','pertinent_symptoms','label','Dizziness','type','boolean','sequence',30,'required',false,'accessibilityLabel','Dizziness','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_chest_pain','sectionKey','pertinent_symptoms','label','Chest pain','type','boolean','sequence',40,'required',false,'accessibilityLabel','Chest pain','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_dyspnea','sectionKey','pertinent_symptoms','label','Dyspnea','type','boolean','sequence',50,'required',false,'accessibilityLabel','Dyspnea','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_sweating','sectionKey','pertinent_symptoms','label','Sweating','type','boolean','sequence',60,'required',false,'accessibilityLabel','Sweating','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_wheezing','sectionKey','pertinent_symptoms','label','Wheezing','type','boolean','sequence',70,'required',false,'accessibilityLabel','Wheezing','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_malaise','sectionKey','pertinent_symptoms','label','Malaise','type','boolean','sequence',80,'required',false,'accessibilityLabel','Malaise','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_sputum','sectionKey','pertinent_symptoms','label','Sputum','type','boolean','sequence',90,'required',false,'accessibilityLabel','Sputum','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_appearance','sectionKey','pertinent_symptoms','label','Appearance','type','text','sequence',100,'required',false,'accessibilityLabel','Sputum appearance','helpText','The legacy form initially displays none.','maxLength',255,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_ops_all_reviewed','sectionKey','pertinent_symptoms','label','All reviewed and negative','type','boolean','sequence',110,'required',false,'accessibilityLabel','All reviewed and negative','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_review_of_pmh','sectionKey','history_review','label','Review of PMH','type','boolean','sequence',10,'required',false,'accessibilityLabel','Review of past medical history','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_review_of_medications','sectionKey','history_review','label','Medications','type','boolean','sequence',20,'required',false,'accessibilityLabel','Review of medications','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_review_of_allergies','sectionKey','history_review','label','Allergies','type','boolean','sequence',30,'required',false,'accessibilityLabel','Review of allergies','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_review_of_sh','sectionKey','history_review','label','Social history','type','boolean','sequence',40,'required',false,'accessibilityLabel','Review of social history','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_review_of_fh','sectionKey','history_review','label','Family history','type','boolean','sequence',50,'required',false,'accessibilityLabel','Review of family history','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitishistory' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitishistory' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis history and symptom-review fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitishistory' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
