insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000020','legacy.bronchitisearnoseexam',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.bronchitisearnoseexam','name','Bronchitis Ear and Nares Examination','purpose','Legacy Bronchitis tympanic-membrane and nares examination compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','ear_nose_exam','title','TM and nares examination','sequence',10,'description','Mapped from the TM''S and NARES checklist portion of the legacy Bronchitis form.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_tms_normal_right','sectionKey','ear_nose_exam','label','TM normal right','type','boolean','sequence',10,'required',false,'accessibilityLabel','Tympanic membrane normal right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_normal_left','sectionKey','ear_nose_exam','label','TM normal left','type','boolean','sequence',20,'required',false,'accessibilityLabel','Tympanic membrane normal left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_normal_right','sectionKey','ear_nose_exam','label','Nares normal right','type','boolean','sequence',30,'required',false,'accessibilityLabel','Nares normal right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_normal_left','sectionKey','ear_nose_exam','label','Nares normal left','type','boolean','sequence',40,'required',false,'accessibilityLabel','Nares normal left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_thickened_right','sectionKey','ear_nose_exam','label','TM thickened right','type','boolean','sequence',50,'required',false,'accessibilityLabel','Tympanic membrane thickened right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_thickened_left','sectionKey','ear_nose_exam','label','TM thickened left','type','boolean','sequence',60,'required',false,'accessibilityLabel','Tympanic membrane thickened left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_swelling_right','sectionKey','ear_nose_exam','label','Nares swelling right','type','boolean','sequence',70,'required',false,'accessibilityLabel','Nares swelling right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_swelling_left','sectionKey','ear_nose_exam','label','Nares swelling left','type','boolean','sequence',80,'required',false,'accessibilityLabel','Nares swelling left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_af_level_right','sectionKey','ear_nose_exam','label','TM A/F level right','type','boolean','sequence',90,'required',false,'accessibilityLabel','Tympanic membrane air fluid level right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_af_level_left','sectionKey','ear_nose_exam','label','TM A/F level left','type','boolean','sequence',100,'required',false,'accessibilityLabel','Tympanic membrane air fluid level left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_discharge_right','sectionKey','ear_nose_exam','label','Nares discharge right','type','boolean','sequence',110,'required',false,'accessibilityLabel','Nares discharge right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_nares_discharge_left','sectionKey','ear_nose_exam','label','Nares discharge left','type','boolean','sequence',120,'required',false,'accessibilityLabel','Nares discharge left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_retracted_right','sectionKey','ear_nose_exam','label','TM retracted right','type','boolean','sequence',130,'required',false,'accessibilityLabel','Tympanic membrane retracted right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_retracted_left','sectionKey','ear_nose_exam','label','TM retracted left','type','boolean','sequence',140,'required',false,'accessibilityLabel','Tympanic membrane retracted left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_bulging_right','sectionKey','ear_nose_exam','label','TM bulging right','type','boolean','sequence',150,'required',false,'accessibilityLabel','Tympanic membrane bulging right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_bulging_left','sectionKey','ear_nose_exam','label','TM bulging left','type','boolean','sequence',160,'required',false,'accessibilityLabel','Tympanic membrane bulging left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_perforated_right','sectionKey','ear_nose_exam','label','TM perforated right','type','boolean','sequence',170,'required',false,'accessibilityLabel','Tympanic membrane perforated right','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_perforated_left','sectionKey','ear_nose_exam','label','TM perforated left','type','boolean','sequence',180,'required',false,'accessibilityLabel','Tympanic membrane perforated left','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_tms_nares_not_examined','sectionKey','ear_nose_exam','label','TM and nares not examined','type','boolean','sequence',190,'required',false,'accessibilityLabel','Tympanic membranes and nares not examined','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitisearnoseexam' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitisearnoseexam' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis tympanic-membrane and nares examination fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitisearnoseexam' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
