insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000024','legacy.bronchitisdiagnosisplan',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with diagnosis_options as (
select jsonb_build_array(
jsonb_build_object('code','none','display','None'),
jsonb_build_object('code','icd9_465_9','display','465.9, URI'),
jsonb_build_object('code','icd9_466_0','display','466.0, Bronchitis, Acute NOS'),
jsonb_build_object('code','icd9_493_92','display','493.92, Asthma, Acute Exac.'),
jsonb_build_object('code','icd9_491_8','display','491.8, Bronchitis, Chronic'),
jsonb_build_object('code','icd9_496_0','display','496.0, COPD'),
jsonb_build_object('code','icd9_491_21','display','491.21, COPD Exacerbation'),
jsonb_build_object('code','icd9_486_0','display','486.0, Pneumonia, Acute'),
jsonb_build_object('code','icd9_519_7','display','519.7, Bronchospasm')) as options
), schema as (
select jsonb_build_object('stableKey','legacy.bronchitisdiagnosisplan','name','Bronchitis Diagnostics Diagnosis and Treatment','purpose','Legacy Bronchitis diagnostic-test, diagnosis, and treatment compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','diagnostic_plan','title','Diagnostic tests diagnosis and treatment','sequence',10,'description','Mapped from the diagnostic-test, diagnosis, additional-diagnosis, and treatment portion of the legacy Bronchitis form.')),'fields',jsonb_build_array(
jsonb_build_object('key','bronchitis_diagnostic_tests','sectionKey','diagnostic_plan','label','Diagnostic tests','type','multiline','sequence',10,'required',false,'accessibilityLabel','Diagnostic tests','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','diagnosis1_bronchitis_form','sectionKey','diagnostic_plan','label','Diagnosis 1','type','select','sequence',20,'required',false,'accessibilityLabel','Diagnosis 1','helpText','Legacy ICD-9 display values use runtime-safe identifiers.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-bronchitis-icd9-v1','options',d.options,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','diagnosis2_bronchitis_form','sectionKey','diagnostic_plan','label','Diagnosis 2','type','select','sequence',30,'required',false,'accessibilityLabel','Diagnosis 2','helpText','Legacy ICD-9 display values use runtime-safe identifiers.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-bronchitis-icd9-v1','options',d.options,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','diagnosis3_bronchitis_form','sectionKey','diagnostic_plan','label','Diagnosis 3','type','select','sequence',40,'required',false,'accessibilityLabel','Diagnosis 3','helpText','Legacy ICD-9 display values use runtime-safe identifiers.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-bronchitis-icd9-v1','options',d.options,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','diagnosis4_bronchitis_form','sectionKey','diagnostic_plan','label','Diagnosis 4','type','select','sequence',50,'required',false,'accessibilityLabel','Diagnosis 4','helpText','Legacy ICD-9 display values use runtime-safe identifiers.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem','legacy-bronchitis-icd9-v1','options',d.options,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_additional_diagnosis','sectionKey','diagnostic_plan','label','Additional diagnosis','type','multiline','sequence',60,'required',false,'accessibilityLabel','Additional diagnosis','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bronchitis_treatment','sectionKey','diagnostic_plan','label','Treatment','type','multiline','sequence',70,'required',false,'accessibilityLabel','Treatment','helpText',null,'maxLength',4000,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json from diagnosis_options d)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.bronchitisdiagnosisplan' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.bronchitisdiagnosisplan' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the bounded legacy Bronchitis diagnostic-test, diagnosis, and treatment fields as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.bronchitisdiagnosisplan' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
