insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000036','legacy.reviewofsystems',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with sources as (
select d.stable_key,r.schema_json from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=d.effective_revision where d.stable_key in ('legacy.reviewofsystemsgeneral','legacy.reviewofsystemsskin','legacy.reviewofsystemsheent','legacy.reviewofsystemspulmonary','legacy.reviewofsystemscardiovascular','legacy.reviewofsystemsgastrointestinal','legacy.reviewofsystemsgenitourinary','legacy.reviewofsystemsmusculoskeletal','legacy.reviewofsystemsendocrine','legacy.reviewofsystemsadditionalnotes')
), source_fields as (
select case stable_key when 'legacy.reviewofsystemsgeneral' then 10 when 'legacy.reviewofsystemsskin' then 20 when 'legacy.reviewofsystemsheent' then 30 when 'legacy.reviewofsystemspulmonary' then 40 when 'legacy.reviewofsystemscardiovascular' then 50 when 'legacy.reviewofsystemsgastrointestinal' then 60 when 'legacy.reviewofsystemsgenitourinary' then 70 when 'legacy.reviewofsystemsmusculoskeletal' then 80 when 'legacy.reviewofsystemsendocrine' then 90 when 'legacy.reviewofsystemsadditionalnotes' then 100 end as source_order,field,ordinal from sources cross join lateral jsonb_array_elements(schema_json->'fields') with ordinality as fields(field,ordinal)
), schema as (
select jsonb_build_object('stableKey','legacy.reviewofsystems','name','Review of Systems Checks','purpose','Unified legacy Review of Systems encounter form compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','general','title','General','sequence',10,'description','Legacy General checklist.'),jsonb_build_object('key','skin','title','Skin','sequence',20,'description','Legacy Skin checklist.'),jsonb_build_object('key','heent','title','HEENT','sequence',30,'description','Legacy HEENT checklist.'),jsonb_build_object('key','pulmonary','title','Pulmonary','sequence',40,'description','Legacy Pulmonary checklist.'),jsonb_build_object('key','cardiovascular','title','Cardiovascular','sequence',50,'description','Legacy Cardiovascular checklist.'),jsonb_build_object('key','gastrointestinal','title','Gastrointestinal','sequence',60,'description','Legacy Gastrointestinal checklist.'),jsonb_build_object('key','genitourinary','title','Genitourinary','sequence',70,'description','Legacy Genitourinary checklist.'),jsonb_build_object('key','musculoskeletal','title','Musculoskeletal','sequence',80,'description','Legacy Musculoskeletal checklist.'),jsonb_build_object('key','endocrine','title','Endocrine','sequence',90,'description','Legacy Endocrine checklist.'),jsonb_build_object('key','additional_notes','title','Additional Notes','sequence',100,'description','Legacy longtext narrative.')),'fields',(select jsonb_agg(field order by source_order,ordinal) from source_fields),'rules','[]'::jsonb) schema_json
)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.reviewofsystems' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.reviewofsystems' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Compose all ten legacy Review of Systems sections into one local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.reviewofsystems' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
