insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000030','legacy.reviewofsystemscardiovascular',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.reviewofsystemscardiovascular','name','Review of Systems Cardiovascular','purpose','Legacy Review of Systems Cardiovascular checklist compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','cardiovascular','title','Cardiovascular','sequence',10,'description','Mapped from the Cardiovascular checklist portion of the legacy Review of Systems Checks form.')),'fields',jsonb_build_array(
jsonb_build_object('key','heart_attack','sectionKey','cardiovascular','label','Heart Attack','type','boolean','sequence',10,'required',false,'accessibilityLabel','Heart Attack','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','irregular_heart_beat','sectionKey','cardiovascular','label','Irregular Heart Beat','type','boolean','sequence',20,'required',false,'accessibilityLabel','Irregular Heart Beat','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','chest_pains','sectionKey','cardiovascular','label','Chest Pains','type','boolean','sequence',30,'required',false,'accessibilityLabel','Chest Pains','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','shortness_of_breath','sectionKey','cardiovascular','label','Shortness of Breath','type','boolean','sequence',40,'required',false,'accessibilityLabel','Shortness of Breath','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','high_blood_pressure','sectionKey','cardiovascular','label','High Blood Pressure','type','boolean','sequence',50,'required',false,'accessibilityLabel','High Blood Pressure','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','heart_failure','sectionKey','cardiovascular','label','Heart Failure','type','boolean','sequence',60,'required',false,'accessibilityLabel','Heart Failure','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','poor_circulation','sectionKey','cardiovascular','label','Poor Circulation','type','boolean','sequence',70,'required',false,'accessibilityLabel','Poor Circulation','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','vascular_surgery','sectionKey','cardiovascular','label','Vascular Surgery','type','boolean','sequence',80,'required',false,'accessibilityLabel','Vascular Surgery','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','cardiac_catheterization','sectionKey','cardiovascular','label','Cardiac Catheterization','type','boolean','sequence',90,'required',false,'accessibilityLabel','Cardiac Catheterization','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','coronary_artery_bypass','sectionKey','cardiovascular','label','Coronary Artery Bypass','type','boolean','sequence',100,'required',false,'accessibilityLabel','Coronary Artery Bypass','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','heart_transplant','sectionKey','cardiovascular','label','Heart Transplant','type','boolean','sequence',110,'required',false,'accessibilityLabel','Heart Transplant','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','stress_test','sectionKey','cardiovascular','label','Stress Test','type','boolean','sequence',120,'required',false,'accessibilityLabel','Stress Test','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.reviewofsystemscardiovascular' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.reviewofsystemscardiovascular' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the complete legacy Review of Systems Cardiovascular checklist as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.reviewofsystemscardiovascular' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
