insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000031','legacy.reviewofsystemsgastrointestinal',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.reviewofsystemsgastrointestinal','name','Review of Systems Gastrointestinal','purpose','Legacy Review of Systems Gastrointestinal checklist compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','gastrointestinal','title','Gastrointestinal','sequence',10,'description','Mapped from the Gastrointestinal checklist portion of the legacy Review of Systems Checks form.')),'fields',jsonb_build_array(
jsonb_build_object('key','stomach_pains','sectionKey','gastrointestinal','label','Stomach Pains','type','boolean','sequence',10,'required',false,'accessibilityLabel','Stomach Pains','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','peptic_ulcer_disease','sectionKey','gastrointestinal','label','Peptic Ulcer Disease','type','boolean','sequence',20,'required',false,'accessibilityLabel','Peptic Ulcer Disease','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','gastritis','sectionKey','gastrointestinal','label','Gastritis','type','boolean','sequence',30,'required',false,'accessibilityLabel','Gastritis','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','endoscopy','sectionKey','gastrointestinal','label','Endoscopy','type','boolean','sequence',40,'required',false,'accessibilityLabel','Endoscopy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','polyps','sectionKey','gastrointestinal','label','Polyps','type','boolean','sequence',50,'required',false,'accessibilityLabel','Polyps','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','colonoscopy','sectionKey','gastrointestinal','label','Colonoscopy','type','boolean','sequence',60,'required',false,'accessibilityLabel','Colonoscopy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','colon_cancer','sectionKey','gastrointestinal','label','Colon Cancer','type','boolean','sequence',70,'required',false,'accessibilityLabel','Colon Cancer','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','colon_cancer_surgery','sectionKey','gastrointestinal','label','Colon Cancer Surgery','type','boolean','sequence',80,'required',false,'accessibilityLabel','Colon Cancer Surgery','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ulcerative_colitis','sectionKey','gastrointestinal','label','Ulcerative Colitis','type','boolean','sequence',90,'required',false,'accessibilityLabel','Ulcerative Colitis','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','crohns_disease','sectionKey','gastrointestinal','label','Crohn''s Disease','type','boolean','sequence',100,'required',false,'accessibilityLabel','Crohn''s Disease','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','appendectomy','sectionKey','gastrointestinal','label','Appendectomy','type','boolean','sequence',110,'required',false,'accessibilityLabel','Appendectomy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','divirticulitis','sectionKey','gastrointestinal','label','Diverticulitis','type','boolean','sequence',120,'required',false,'accessibilityLabel','Diverticulitis','helpText','Legacy persisted field spelling retained for compatibility.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','divirticulitis_surgery','sectionKey','gastrointestinal','label','Diverticulitis Surgery','type','boolean','sequence',130,'required',false,'accessibilityLabel','Diverticulitis Surgery','helpText','Legacy persisted field spelling retained for compatibility.','maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','gall_stones','sectionKey','gastrointestinal','label','Gall Stones','type','boolean','sequence',140,'required',false,'accessibilityLabel','Gall Stones','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','cholecystectomy','sectionKey','gastrointestinal','label','Cholecystectomy','type','boolean','sequence',150,'required',false,'accessibilityLabel','Cholecystectomy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','hepatitis','sectionKey','gastrointestinal','label','Hepatitis','type','boolean','sequence',160,'required',false,'accessibilityLabel','Hepatitis','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','cirrhosis_of_the_liver','sectionKey','gastrointestinal','label','Cirrhosis of the Liver','type','boolean','sequence',170,'required',false,'accessibilityLabel','Cirrhosis of the Liver','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','splenectomy','sectionKey','gastrointestinal','label','Splenectomy','type','boolean','sequence',180,'required',false,'accessibilityLabel','Splenectomy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.reviewofsystemsgastrointestinal' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.reviewofsystemsgastrointestinal' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the complete legacy Review of Systems Gastrointestinal checklist with persisted field keys.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.reviewofsystemsgastrointestinal' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
