insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000032','legacy.reviewofsystemsgenitourinary',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.reviewofsystemsgenitourinary','name','Review of Systems Genitourinary','purpose','Legacy Review of Systems Genitourinary checklist compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','genitourinary','title','Genitourinary','sequence',10,'description','Mapped from the Genitourinary checklist portion of the legacy Review of Systems Checks form.')),'fields',jsonb_build_array(
jsonb_build_object('key','kidney_failure','sectionKey','genitourinary','label','Kidney Failure','type','boolean','sequence',10,'required',false,'accessibilityLabel','Kidney Failure','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','kidney_stones','sectionKey','genitourinary','label','Kidney Stones','type','boolean','sequence',20,'required',false,'accessibilityLabel','Kidney Stones','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','kidney_cancer','sectionKey','genitourinary','label','Kidney Cancer','type','boolean','sequence',30,'required',false,'accessibilityLabel','Kidney Cancer','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','kidney_infections','sectionKey','genitourinary','label','Kidney Infections','type','boolean','sequence',40,'required',false,'accessibilityLabel','Kidney Infections','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bladder_infections','sectionKey','genitourinary','label','Bladder Infections','type','boolean','sequence',50,'required',false,'accessibilityLabel','Bladder Infections','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bladder_cancer','sectionKey','genitourinary','label','Bladder Cancer','type','boolean','sequence',60,'required',false,'accessibilityLabel','Bladder Cancer','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','prostate_problems','sectionKey','genitourinary','label','Prostate Problems','type','boolean','sequence',70,'required',false,'accessibilityLabel','Prostate Problems','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','prostate_cancer','sectionKey','genitourinary','label','Prostate Cancer','type','boolean','sequence',80,'required',false,'accessibilityLabel','Prostate Cancer','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','kidney_transplant','sectionKey','genitourinary','label','Kidney Transplant','type','boolean','sequence',90,'required',false,'accessibilityLabel','Kidney Transplant','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','sexually_transmitted_disease','sectionKey','genitourinary','label','Sexually Transmitted Disease','type','boolean','sequence',100,'required',false,'accessibilityLabel','Sexually Transmitted Disease','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','burning_with_urination','sectionKey','genitourinary','label','Burning with Urination','type','boolean','sequence',110,'required',false,'accessibilityLabel','Burning with Urination','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','discharge_from_urethra','sectionKey','genitourinary','label','Discharge From Urethra','type','boolean','sequence',120,'required',false,'accessibilityLabel','Discharge From Urethra','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.reviewofsystemsgenitourinary' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.reviewofsystemsgenitourinary' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the complete legacy Review of Systems Genitourinary checklist as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.reviewofsystemsgenitourinary' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
