insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000028','legacy.reviewofsystemsheent',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed')
on conflict(stable_key) do nothing;

with schema as (
select jsonb_build_object('stableKey','legacy.reviewofsystemsheent','name','Review of Systems HEENT','purpose','Legacy Review of Systems HEENT checklist compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','heent','title','HEENT','sequence',10,'description','Mapped from the HEENT checklist portion of the legacy Review of Systems Checks form.')),'fields',jsonb_build_array(
jsonb_build_object('key','cataracts','sectionKey','heent','label','Cataracts','type','boolean','sequence',10,'required',false,'accessibilityLabel','Cataracts','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','cataract_surgery','sectionKey','heent','label','Cataract Surgery','type','boolean','sequence',20,'required',false,'accessibilityLabel','Cataract Surgery','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','glaucoma','sectionKey','heent','label','Glaucoma','type','boolean','sequence',30,'required',false,'accessibilityLabel','Glaucoma','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','double_vision','sectionKey','heent','label','Double Vision','type','boolean','sequence',40,'required',false,'accessibilityLabel','Double Vision','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','blurred_vision','sectionKey','heent','label','Blurred Vision','type','boolean','sequence',50,'required',false,'accessibilityLabel','Blurred Vision','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','poor_hearing','sectionKey','heent','label','Poor Hearing','type','boolean','sequence',60,'required',false,'accessibilityLabel','Poor Hearing','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','headaches','sectionKey','heent','label','Headaches','type','boolean','sequence',70,'required',false,'accessibilityLabel','Headaches','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','ringing_in_ears','sectionKey','heent','label','Ringing in Ears','type','boolean','sequence',80,'required',false,'accessibilityLabel','Ringing in Ears','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','bloody_nose','sectionKey','heent','label','Bloody Nose','type','boolean','sequence',90,'required',false,'accessibilityLabel','Bloody Nose','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','sinusitis','sectionKey','heent','label','Sinusitis','type','boolean','sequence',100,'required',false,'accessibilityLabel','Sinusitis','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','sinus_surgery','sectionKey','heent','label','Sinus Surgery','type','boolean','sequence',110,'required',false,'accessibilityLabel','Sinus Surgery','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','dry_mouth','sectionKey','heent','label','Dry Mouth','type','boolean','sequence',120,'required',false,'accessibilityLabel','Dry Mouth','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','strep_throat','sectionKey','heent','label','Strep Throat','type','boolean','sequence',130,'required',false,'accessibilityLabel','Strep Throat','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','tonsillectomy','sectionKey','heent','label','Tonsillectomy','type','boolean','sequence',140,'required',false,'accessibilityLabel','Tonsillectomy','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','swollen_lymph_nodes','sectionKey','heent','label','Swollen Lymph Nodes','type','boolean','sequence',150,'required',false,'accessibilityLabel','Swollen Lymph Nodes','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','throat_cancer','sectionKey','heent','label','Throat Cancer','type','boolean','sequence',160,'required',false,'accessibilityLabel','Throat Cancer','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false),
jsonb_build_object('key','throat_cancer_surgery','sectionKey','heent','label','Throat Cancer Surgery','type','boolean','sequence',170,'required',false,'accessibilityLabel','Throat Cancer Surgery','helpText',null,'maxLength',null,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options','[]'::jsonb,'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false)),'rules','[]'::jsonb) schema_json)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by) select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.reviewofsystemsheent' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.reviewofsystemsheent' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the complete legacy Review of Systems HEENT checklist as a local compatibility form.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.reviewofsystemsheent' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
