insert into clinical_form_definitions(definition_id,stable_key,latest_revision,effective_revision,created_at,created_by,updated_at,updated_by)
values('90f00000-0000-4000-8000-000000000037','legacy.roseyes',1,null,now(),'legacy-adoption-seed',now(),'legacy-adoption-seed') on conflict(stable_key) do nothing;

with fields as (
  select jsonb_agg(jsonb_build_object('key',key,'sectionKey','eyes','label',label,'type','text','sequence',sequence,'required',false,'accessibilityLabel',label,'helpText','Legacy three-state Review of Systems value: Yes, No, or N/A.','maxLength',3,'minimum',null,'maximum',null,'precision',null,'unit',null,'codeSystem',null,'options',jsonb_build_array(jsonb_build_object('value','Yes','label','Yes'),jsonb_build_object('value','No','label','No'),jsonb_build_object('value','N/A','label','N/A')),'repeatMinimum',null,'repeatMaximum',null,'children','[]'::jsonb,'readOnly',false) order by sequence) value
  from (values ('change_in_vision','Change in vision',10),('glaucoma_history','Glaucoma history',20),('eye_pain','Eye pain',30),('irritation','Eye irritation',40),('redness','Eye redness',50),('excessive_tearing','Excessive tearing',60),('double_vision','Double vision',70),('blind_spots','Blind spots',80),('photophobia','Photophobia',90)) as source(key,label,sequence)
), schema as (select jsonb_build_object('stableKey','legacy.roseyes','name','Review of Systems Eyes','purpose','Legacy Review of Systems eyes compatibility capture.','contextScope','encounter','owningService','clinical_operations','capability','encounters.auth_a','signaturePolicy','author-only','sections',jsonb_build_array(jsonb_build_object('key','eyes','title','Eyes','sequence',10,'description','Mapped from legacy form_ros eye fields.')),'fields',fields.value,'rules','[]'::jsonb) schema_json from fields)
insert into clinical_form_revisions(definition_id,revision,status,version,schema_json,renderer_version,schema_hash,author,reviewed_by,approved_by,effective_from,predecessor_revision,created_at,updated_at,updated_by)
select d.definition_id,1,'effective',3,s.schema_json,'local-clinical-form-renderer-v1',encode(sha256(convert_to(s.schema_json::text,'utf8')),'hex'),'legacy-adoption-seed','legacy-adoption-seed','legacy-adoption-seed',now(),null,now(),now(),'legacy-adoption-seed' from clinical_form_definitions d cross join schema s where d.stable_key='legacy.roseyes' on conflict(definition_id,revision) do nothing;
update clinical_form_definitions set effective_revision=1,updated_at=now(),updated_by='legacy-adoption-seed' where stable_key='legacy.roseyes' and effective_revision is null;
insert into clinical_form_definition_events(definition_id,revision,action,from_status,to_status,actor,reason,occurred_at,snapshot_hash) select d.definition_id,1,'legacy-adopted-effective',null,'effective','legacy-adoption-seed','Adopt the legacy form_ros eye fields with their three-state values.',now(),r.schema_hash from clinical_form_definitions d join clinical_form_revisions r on r.definition_id=d.definition_id and r.revision=1 where d.stable_key='legacy.roseyes' and not exists(select 1 from clinical_form_definition_events e where e.definition_id=d.definition_id and e.revision=1 and e.action='legacy-adopted-effective');
