// SPDX-FileCopyrightText: 2026 Neil Kimber and AvenChart contributors
// SPDX-License-Identifier: GPL-3.0-or-later

namespace AvenChart.Api.Features.Telehealth;

public sealed record TelehealthPracticeContextResponse(
    bool Available,
    string PracticeDisplayName,
    IReadOnlyList<string> SupportedStates,
    bool SyntheticOnly,
    string EntryMessage);

public sealed record CreateTelehealthProspectiveApplicantRequest(
    string LegalFirstName,
    string LegalLastName,
    string DateOfBirth,
    string Email,
    string Phone,
    string ResidenceStateCode,
    string PostalCode,
    bool SyntheticDataConfirmed);

public sealed record VerifyTelehealthProspectiveApplicantContactRequest(
    int ExpectedVersion,
    string VerificationCode);

public sealed record EvaluateTelehealthProspectiveSafetyTriageRequest(
    int ExpectedVersion,
    string CurrentLocationStateCode,
    bool? CurrentLocationConfirmed,
    bool? HasEmergencyWarning,
    bool? SevereOrWorsening,
    bool? RequiresHandsOnExam,
    bool? Unsure,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectiveSafetyTriageResponse(
    Guid EvaluationId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string SafetyDisposition,
    string CurrentLocationStateCode,
    string ProtocolKey,
    int ProtocolVersion,
    DateTimeOffset EvaluatedAt,
    bool MayContinueProspectiveIntake,
    bool IdentityProofed,
    bool ClinicalReviewPerformed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool ProspectiveIntakeCompleted,
    bool CoverageChecked,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectiveVisitPurposeRequest(
    int ExpectedVersion,
    string PurposeCategory,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectiveVisitPurposeResponse(
    Guid PurposeId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string PurposeCategory,
    string PurposeDisplayLabel,
    DateTimeOffset RecordedAt,
    bool ClinicalProtocolPublished,
    bool ClinicalEligibilityDetermined,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool ProspectiveIntakeCompleted,
    bool CoverageChecked,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectivePracticeNetworkPrecheckRequest(
    int ExpectedVersion,
    string PlanKey,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectivePracticeNetworkOptionResponse(
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string PracticeNetworkStatus,
    string Meaning);

public sealed record TelehealthProspectivePracticeNetworkOptionsResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string AdapterMode,
    string CatalogKey,
    int CatalogVersion,
    DateTimeOffset CatalogEffectiveFrom,
    DateTimeOffset CatalogEffectiveThrough,
    IReadOnlyList<TelehealthProspectivePracticeNetworkOptionResponse> Plans,
    bool MemberEligibilityChecked,
    bool MemberBenefitsChecked,
    bool RenderingPhysicianNetworkChecked,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthProspectivePracticeNetworkPrecheckResponse(
    Guid PrecheckId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string PurposeCategory,
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string PracticeNetworkStatus,
    string AdapterMode,
    string CatalogKey,
    int CatalogVersion,
    DateTimeOffset CatalogEffectiveFrom,
    DateTimeOffset CatalogEffectiveThrough,
    DateTimeOffset RecordedAt,
    bool MemberEligibilityChecked,
    bool MemberBenefitsChecked,
    bool RenderingPhysicianNetworkChecked,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool CoverageRecordCreated,
    bool EstimateCreated,
    bool FinancialAcknowledgmentCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareEnabled,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool CommunicationEnabled,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectiveMemberInsuranceDetailsRequest(
    int ExpectedVersion,
    string MemberId,
    string? GroupNumber,
    string SubscriberRelationship,
    string? SubscriberFirstName,
    string? SubscriberLastName,
    string? SubscriberDateOfBirth,
    bool DetailsConfirmed,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectiveMemberInsuranceDetailsResponse(
    Guid DetailsId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string PurposeCategory,
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string PracticeNetworkStatus,
    string MemberIdMask,
    string? GroupNumberMask,
    string SubscriberRelationship,
    string CoveragePriority,
    string ProtectionScheme,
    int ProtectionVersion,
    DateTimeOffset RecordedAt,
    bool MemberMatched,
    bool MemberEligibilityChecked,
    bool MemberBenefitsChecked,
    bool RenderingPhysicianNetworkChecked,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool CoverageRecordCreated,
    bool EstimateCreated,
    bool FinancialAcknowledgmentCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareEnabled,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool CommunicationEnabled,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectiveEligibilityRequest(
    int ExpectedVersion,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectiveEligibilityResponse(
    Guid EligibilityResultId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string PurposeCategory,
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string PracticeNetworkStatus,
    string MemberIdMask,
    string? GroupNumberMask,
    string SubscriberRelationship,
    string CoveragePriority,
    DateOnly DateOfService,
    string ServiceCategory,
    string AdapterMode,
    string CompatibilityTarget,
    string DatasetKey,
    int DatasetVersion,
    DateTimeOffset DatasetEffectiveFrom,
    DateTimeOffset DatasetEffectiveThrough,
    Guid InquiryTraceToken,
    Guid ResponseTraceToken,
    string TransportOutcome,
    string MemberMatchStatus,
    string EligibilityStatus,
    string BenefitInformationStatus,
    string BusinessOutcome,
    bool MemberMatched,
    bool MemberEligibilityChecked,
    bool MemberBenefitsChecked,
    DateTimeOffset CheckedAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset RecordedAt,
    bool RawTransactionCreated,
    bool RenderingPhysicianNetworkChecked,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool CoverageRecordCreated,
    bool EstimateCreated,
    bool FinancialAcknowledgmentCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareEnabled,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool CommunicationEnabled,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectivePracticeNetworkRequest(
    int ExpectedVersion,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectivePracticeNetworkResponse(
    Guid NetworkDeterminationId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string PurposeCategory,
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string PracticeDisplayName,
    DateOnly DateOfService,
    string ServiceCategory,
    string EligibilityStatus,
    string BenefitInformationStatus,
    string EligibilityBusinessOutcome,
    DateTimeOffset EligibilityCheckedAt,
    DateTimeOffset EligibilityExpiresAt,
    string AdapterMode,
    string CompatibilityTarget,
    string DatasetKey,
    int DatasetVersion,
    DateTimeOffset DatasetEffectiveFrom,
    DateTimeOffset DatasetEffectiveThrough,
    DateTimeOffset SourceLastUpdatedAt,
    Guid RequestTraceToken,
    Guid ResponseTraceToken,
    string TransportOutcome,
    string PlanNetworkMatchStatus,
    string PracticeAffiliationStatus,
    string ServiceAvailabilityStatus,
    string NewPatientAcceptanceStatus,
    string BusinessOutcome,
    bool PracticeNetworkChecked,
    bool PracticeInNetwork,
    bool NewPatientsAccepted,
    string? NetworkReference,
    string? OrganizationReference,
    string? LocationReference,
    string? ServiceReference,
    DateTimeOffset CheckedAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset RecordedAt,
    bool FhirResourceCreated,
    bool LiveDirectoryQueried,
    bool RenderingPhysicianNetworkChecked,
    bool ExactNetworkConfirmed,
    bool CoverageVerified,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool CoverageRecordCreated,
    bool EstimateCreated,
    bool FinancialAcknowledgmentCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareEnabled,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool CommunicationEnabled,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthProspectiveIdentityProofingRequest(
    int ExpectedVersion,
    bool PrivacyNoticeAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthProspectiveIdentityProofingResponse(
    Guid IdentityProofingResultId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string PlanKey,
    string PrivacyNoticeKey,
    int PrivacyNoticeVersion,
    bool PrivacyNoticeAcknowledged,
    string AdapterMode,
    string CompatibilityTarget,
    string PracticeStatementKey,
    int PracticeStatementVersion,
    string DatasetKey,
    int DatasetVersion,
    DateTimeOffset DatasetEffectiveFrom,
    DateTimeOffset DatasetEffectiveThrough,
    DateTimeOffset SourceLastUpdatedAt,
    Guid RequestTraceToken,
    Guid ResponseTraceToken,
    string ProofingMethod,
    string TransportOutcome,
    string EvidenceCollectionStatus,
    string EvidenceValidationStatus,
    string AttributeValidationStatus,
    string ApplicantVerificationStatus,
    string FraudCheckStatus,
    string BusinessOutcome,
    string ProofingSessionReference,
    string EvidencePackageReference,
    DateTimeOffset CheckedAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset RecordedAt,
    string AssuranceLevelAchieved,
    bool IdentityEvidenceCollected,
    bool GovernmentIdentifierCollected,
    bool BiometricDataCollected,
    bool AuthoritativeSourceQueried,
    bool ProofingNotificationSent,
    bool RedressCaseCreated,
    bool AuthenticatorBound,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool CoverageRecordCreated,
    bool EstimateCreated,
    bool FinancialAcknowledgmentCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareEnabled,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool CommunicationEnabled,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthProspectiveApplicantResponse(
    Guid ApplicantId,
    string Status,
    int Version,
    string PracticeDisplayName,
    string ResidenceStateCode,
    string MaskedEmail,
    string MaskedPhone,
    bool ContactVerified,
    string IdentityAssurance,
    string? DuplicateDisposition,
    bool CanonicalPatientCreated,
    int VerificationAttemptsRemaining,
    DateTimeOffset ExpiresAt,
    string? DemonstrationVerificationCode,
    string NextAction,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthApplicantIdentityReviewItemResponse(
    Guid ApplicantId,
    int Version,
    string Status,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    DateTimeOffset ContactVerifiedAt,
    string DuplicateDisposition,
    string AllowedDecision,
    DateTimeOffset CreatedAt,
    DateTimeOffset ExpiresAt);

public sealed record TelehealthApplicantIdentityReviewQueueResponse(
    string PracticeDisplayName,
    DateTimeOffset ServerTime,
    IReadOnlyList<TelehealthApplicantIdentityReviewItemResponse> Applicants,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantIdentityReviewRequest(
    int ExpectedVersion,
    string Decision,
    string Reason,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantIdentityReviewDecisionResponse(
    Guid DecisionId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string Decision,
    string Reason,
    string PolicyKey,
    int PolicyVersion,
    string EvidenceType,
    DateTimeOffset DecidedAt,
    bool IdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool ProspectiveIntakeCompleted,
    bool RequestCreated,
    bool QueueEnabled,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthApplicantPromotionAuthorizationItemResponse(
    Guid ApplicantId,
    int Version,
    string Status,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    string PlanKey,
    string PayerDisplayName,
    string ProductDisplayName,
    string EligibilityStatus,
    string BenefitInformationStatus,
    string EligibilityBusinessOutcome,
    string NetworkBusinessOutcome,
    string ProofingMethod,
    string TransportOutcome,
    string EvidenceCollectionStatus,
    string EvidenceValidationStatus,
    string AttributeValidationStatus,
    string ApplicantVerificationStatus,
    string FraudCheckStatus,
    string ProofingBusinessOutcome,
    string AssuranceLevelAchieved,
    bool IdentityProofed,
    DateTimeOffset ProofingCheckedAt,
    DateTimeOffset ProofingExpiresAt,
    DateTimeOffset CreatedAt,
    DateTimeOffset ApplicantExpiresAt,
    IReadOnlyList<string> AllowedDecisions);

public sealed record TelehealthApplicantPromotionAuthorizationQueueResponse(
    string PracticeDisplayName,
    DateTimeOffset ServerTime,
    IReadOnlyList<TelehealthApplicantPromotionAuthorizationItemResponse> Applicants,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantPromotionAuthorizationRequest(
    int ExpectedVersion,
    string Decision,
    string Reason,
    bool NoneAssuranceAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantPromotionAuthorizationDecisionResponse(
    Guid DecisionId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string Decision,
    string Reason,
    string PolicyKey,
    int PolicyVersion,
    string EvidenceType,
    DateTimeOffset DecidedAt,
    bool NoneAssuranceAcknowledged,
    bool RealIdentityProofed,
    bool CanonicalPatientCreated,
    bool ChartLinked,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool RequestCreated,
    bool QueueEnabled,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthApplicantSyntheticPromotionItemResponse(
    Guid ApplicantId,
    int Version,
    string Status,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    string AuthorizationDecision,
    DateTimeOffset AuthorizedAt,
    string AssuranceLevelAchieved,
    bool IdentityProofed,
    DateTimeOffset ApplicantExpiresAt,
    DateTimeOffset ProofingExpiresAt,
    string AllowedCommand);

public sealed record TelehealthApplicantSyntheticPromotionQueueResponse(
    string PracticeDisplayName,
    DateTimeOffset ServerTime,
    IReadOnlyList<TelehealthApplicantSyntheticPromotionItemResponse> Applicants,
    IReadOnlyList<string> Limitations);

public sealed record ExecuteTelehealthApplicantSyntheticPromotionRequest(
    int ExpectedVersion,
    string Command,
    string Reason,
    bool CanonicalPatientCreationAcknowledged,
    bool NoPortalNoCareAcknowledged);

public sealed record TelehealthApplicantSyntheticPromotionResponse(
    Guid PromotionId,
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string Outcome,
    bool PossibleMatchDetected,
    bool CanonicalPatientCreated,
    string PolicyKey,
    int PolicyVersion,
    string EvidenceType,
    DateTimeOffset ExecutedAt,
    bool PortalAccountCreated,
    bool ProspectiveIntakeCompleted,
    bool ConsentCreated,
    bool PracticeAccepted,
    bool InsuranceCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    IReadOnlyList<string> Limitations);

public sealed record CreateTelehealthRequest(string ComplaintCategory);
public sealed record ConfirmTelehealthLocationRequest(string StateCode, int ExpectedVersion);
public sealed record EvaluateTelehealthTriageRequest(
    bool HasEmergencyWarning,
    bool SevereOrWorsening,
    bool RequiresHandsOnExam,
    bool Unsure,
    int ExpectedVersion);
public sealed record AuthorizeTelehealthRequest(int ExpectedVersion);
public sealed record CompleteTelehealthReadinessRequest(
    int ExpectedVersion,
    string DemographicsFingerprint,
    string ClinicalSummaryFingerprint,
    bool DemographicsConfirmed,
    bool ContactConfirmed,
    bool ClinicalSummaryConfirmed,
    string ComplaintSummary,
    string SymptomDuration,
    bool SyntheticDataConfirmed,
    string CoverageToken,
    string CoverageFingerprint,
    bool CoverageConfirmed,
    string AcknowledgmentPackageKey,
    int AcknowledgmentPackageVersion,
    string AcknowledgmentContentHash,
    bool AcknowledgmentAccepted);
public sealed record VerifyTelehealthCoverageRequest(int ExpectedVersion);
public sealed record PrepareTelehealthConnectionRequest(
    int ExpectedVersion,
    bool BrowserSupported,
    bool CameraAvailable,
    bool MicrophoneAvailable,
    bool SpeakerAvailable,
    string NetworkQuality,
    bool SyntheticDataConfirmed);
public sealed record StartTelehealthConsultationRequest(
    int ExpectedVersion,
    string PatientLocationState,
    bool PatientIdentityDiscussed,
    bool CallbackConfirmed,
    bool PrivacyConfirmed,
    bool ConsentDiscussed,
    bool NoConcerningSymptomChange,
    bool EmergencyPlanConfirmed,
    bool CommunicationSufficient,
    bool SyntheticDataConfirmed);

public sealed record TelehealthPatientDetailsResponse(
    string DisplayName,
    string DateOfBirth,
    string? Email,
    string? Phone,
    string Address,
    string Fingerprint,
    IReadOnlyList<string> MissingFields);

public sealed record TelehealthClinicalSummaryResponse(
    int ActiveMedicationCount,
    int ActiveAllergyCount,
    bool HistoryAvailable,
    string Fingerprint);

public sealed record TelehealthCoverageOptionResponse(
    string CoverageToken,
    string CoverageType,
    string Provider,
    string PlanName,
    string MaskedPolicyNumber,
    string MaskedGroupNumber,
    string SubscriberRelationship,
    string Fingerprint);

public sealed record TelehealthAcknowledgmentPackageResponse(
    string Kind,
    string PackageKey,
    int PackageVersion,
    string ContentHash,
    string Title,
    IReadOnlyList<string> Statements,
    bool LegalEffect);

public sealed record TelehealthPatientReadinessResponse(
    Guid RequestId,
    int RequestVersion,
    string Status,
    TelehealthPatientDetailsResponse PatientDetails,
    TelehealthClinicalSummaryResponse ClinicalSummary,
    IReadOnlyList<TelehealthCoverageOptionResponse> CoverageOptions,
    TelehealthAcknowledgmentPackageResponse Acknowledgment,
    IReadOnlyList<string> BlockingReasons);

public sealed record TelehealthCoverageStatusResponse(
    string AdapterMode,
    string EligibilityStatus,
    string NetworkStatus,
    string FinancialRoute,
    IReadOnlyList<string> Limitations,
    DateTimeOffset VerifiedAt,
    DateTimeOffset ExpiresAt);

public sealed record TelehealthRequestResponse(
    Guid RequestId,
    string Status,
    string ComplaintCategory,
    string? TriageOutcome,
    int Version,
    string? StateCode,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ReadyAt,
    IReadOnlyList<string> AllowedActions,
    TelehealthCoverageStatusResponse? Coverage);

public sealed record TelehealthRequestListResponse(IReadOnlyList<TelehealthRequestResponse> Requests);

public sealed record TelehealthPatientQueueStatusResponse(
    Guid RequestId,
    string RequestStatus,
    int RequestVersion,
    string Phase,
    string Headline,
    string Detail,
    int? ApproximateRequestsAhead,
    bool PositionIsApproximate,
    bool WaitEstimateAvailable,
    string WaitEstimateMessage,
    DateTimeOffset RequestUpdatedAt,
    DateTimeOffset SnapshotAt,
    int RefreshAfterSeconds,
    bool RealtimeAvailable,
    IReadOnlyList<string> SafetyActions);

public sealed record TelehealthOperationalReviewItem(
    Guid RequestId,
    string Status,
    string ComplaintCategory,
    string TriageOutcome,
    int Version,
    DateTimeOffset CreatedAt);

public sealed record TelehealthOperationalReviewResponse(IReadOnlyList<TelehealthOperationalReviewItem> Requests);

public sealed record TelehealthShiftResponse(
    Guid ShiftId,
    string Status,
    int FacilityId,
    int ClinicianStaffId,
    DateTimeOffset StartedAt,
    int Version);

public sealed record TelehealthReservationResponse(
    Guid ReservationId,
    Guid RequestId,
    Guid QueueEntryId,
    Guid ShiftId,
    int ClinicianStaffId,
    DateTimeOffset ReservedAt,
    DateTimeOffset LeaseExpiresAt,
    string Status,
    int RequestVersion);

public sealed record TelehealthQueueResponse(IReadOnlyList<TelehealthOperationalReviewItem> Requests);

public sealed record TelehealthConnectionGrantResponse(
    Guid SessionId,
    Guid GrantId,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string ParticipantRole,
    string AdapterMode,
    string JoinCredential,
    DateTimeOffset ExpiresAt,
    bool RecordingEnabled,
    bool TranscriptionEnabled,
    bool MediaTransportEnabled,
    string WaitingRoomMessage,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthConsultationStartResponse(
    Guid ConsultationId,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string AppointmentStatus,
    string Modality,
    DateTimeOffset StartedAt,
    bool LegalEffect,
    bool ChartAccessEnabled,
    bool DocumentationEnabled,
    bool PrescribingEnabled,
    bool ClaimsEnabled,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthConsultationPatientResponse(
    string DisplayName,
    string DateOfBirth,
    int Age,
    string? RecordedSex,
    string? CallbackPhone);

public sealed record TelehealthConsultationVisitResponse(
    string PatientLocationState,
    string ComplaintCategory,
    string ComplaintSummary,
    string SymptomDuration,
    string TriageOutcome);

public sealed record TelehealthConsultationAllergyResponse(
    string Title,
    string? Reaction,
    string? Severity);

public sealed record TelehealthConsultationMedicationResponse(string Title);

public sealed record TelehealthConsultationProblemResponse(
    string Title,
    string? Diagnosis);

public sealed record TelehealthConsultationDocumentationDraftRequest(
    int ExpectedVersion,
    string? Subjective,
    string? Objective,
    string? Assessment,
    string? Plan);

public sealed record TelehealthConsultationDocumentationDraftResponse(
    int Version,
    string? SavedAt,
    string? SavedBy,
    bool IsLocked,
    bool IsSigned,
    bool IsFinal,
    string? Subjective,
    string? Objective,
    string? Assessment,
    string? Plan);

public sealed record EnterTelehealthConsultationWrapUpRequest(
    int ExpectedVersion,
    bool SyntheticSessionEndedConfirmed,
    bool DocumentationStillIncompleteAcknowledged,
    bool WrapUpResponsibilityAcknowledged);

public sealed record TelehealthConsultationWrapUpResponse(
    Guid ConsultationId,
    int Version,
    string ConsultationStatus,
    DateTimeOffset MediaEndedAt,
    int RequestVersion,
    string RequestStatus,
    string ShiftStatus,
    string AppointmentStatus,
    bool DocumentationEnabled,
    bool CompletionEnabled,
    bool ClinicianAvailableForNewWork,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthConsultationWorkspaceResponse(
    Guid ConsultationId,
    string ConsultationStatus,
    int ConsultationVersion,
    DateTimeOffset? MediaEndedAt,
    string Modality,
    DateTimeOffset StartedAt,
    DateTimeOffset AsOf,
    bool ReadOnly,
    TelehealthConsultationPatientResponse Patient,
    TelehealthConsultationVisitResponse Visit,
    IReadOnlyList<TelehealthConsultationAllergyResponse> Allergies,
    IReadOnlyList<TelehealthConsultationMedicationResponse> Medications,
    IReadOnlyList<TelehealthConsultationProblemResponse> Problems,
    TelehealthConsultationDocumentationDraftResponse Documentation,
    bool DocumentationEnabled,
    bool PrescribingEnabled,
    bool ClaimsEnabled,
    bool CompletionEnabled,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthPharmacyChoiceRequest(
    int ExpectedVersion,
    Guid DirectoryEntryId,
    bool PatientChoiceConfirmed,
    bool SyntheticDataConfirmed);

public sealed record TelehealthPharmacyAddressResponse(
    string Line1,
    string? Line2,
    string City,
    string State,
    string PostalCode,
    string Country);

public sealed record TelehealthPharmacyDirectoryEntryResponse(
    Guid DirectoryEntryId,
    string Name,
    TelehealthPharmacyAddressResponse Address,
    string Phone,
    string? NcpdpId,
    string? Npi,
    string ElectronicRoutingCapability,
    bool IsChartPreferred,
    decimal? ApproximateDistanceMiles);

public sealed record TelehealthPharmacyChoiceDraftResponse(
    int Version,
    Guid DirectoryEntryId,
    string Name,
    TelehealthPharmacyAddressResponse Address,
    string Phone,
    string? NcpdpId,
    string? Npi,
    string ElectronicRoutingCapability,
    string DirectorySource,
    string DirectoryVersion,
    string ChoiceBasis,
    bool PatientChoiceConfirmed,
    DateTimeOffset SelectedAt,
    bool PrescriptionCreated,
    bool Transmitted);

public sealed record TelehealthPharmacyChoiceWorkspaceResponse(
    Guid ConsultationId,
    string ConsultationStatus,
    string AdapterMode,
    string DatasetId,
    string DatasetVersion,
    DateTimeOffset AsOf,
    string? SearchState,
    string? SearchPostalCode,
    string? DistanceOrigin,
    bool LocationSearchAcknowledged,
    int ChartPreferenceCount,
    IReadOnlyList<TelehealthPharmacyDirectoryEntryResponse> Pharmacies,
    TelehealthPharmacyChoiceDraftResponse? CurrentChoice,
    bool PrescriptionEnabled,
    bool TransmissionEnabled,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthSafetyDispositionDraftRequest(
    int ExpectedVersion,
    string DispositionCode,
    bool AdequateEvaluationCompleted,
    string FollowUpOwner,
    string FollowUpTimeframe,
    string NextStepInstructions,
    string WarningEscalationInstructions,
    string CommunicationMethod,
    bool CommunicationCompleted,
    bool LocationCallbackReconfirmed,
    bool EmergencyInstructionProvided,
    string? EmergencyHandoffStatus,
    string? ContactAttemptSummary,
    bool SyntheticDataConfirmed);

public sealed record TelehealthSafetyDispositionOptionResponse(
    string Code,
    string Label,
    bool RequiresAdequateEvaluation,
    bool RequiresLocationCallbackReconfirmation,
    bool RequiresEmergencyFacts,
    bool RequiresContactAttemptSummary);

public sealed record TelehealthSafetyDispositionDraftResponse(
    int Version,
    string DispositionCode,
    bool AdequateEvaluationCompleted,
    string FollowUpOwner,
    string FollowUpTimeframe,
    string NextStepInstructions,
    string WarningEscalationInstructions,
    string CommunicationMethod,
    bool CommunicationCompleted,
    bool LocationCallbackReconfirmed,
    bool EmergencyInstructionProvided,
    string? EmergencyHandoffStatus,
    string? ContactAttemptSummary,
    DateTimeOffset RecordedAt,
    bool LegalEffect,
    bool Signed,
    bool Finalized,
    bool PatientDelivered);

public sealed record TelehealthSafetyDispositionWorkspaceResponse(
    Guid ConsultationId,
    string ConsultationStatus,
    DateTimeOffset AsOf,
    IReadOnlyList<TelehealthSafetyDispositionOptionResponse> Dispositions,
    IReadOnlyList<string> FollowUpOwners,
    IReadOnlyList<string> CommunicationMethods,
    IReadOnlyList<string> EmergencyHandoffStatuses,
    TelehealthSafetyDispositionDraftResponse? CurrentDraft,
    bool SigningEnabled,
    bool PatientDeliveryEnabled,
    bool CompletionEnabled,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthDocumentationPresenceResponse(
    int Version,
    bool HasAnyContent,
    bool SubjectivePresent,
    bool ObjectivePresent,
    bool AssessmentPresent,
    bool PlanPresent);

public sealed record TelehealthDispositionPresenceResponse(
    int Version,
    string DispositionCode,
    bool AdequateEvaluationCompleted,
    bool FollowUpOwnerPresent,
    bool FollowUpTimeframePresent,
    bool NextStepInstructionsPresent,
    bool WarningEscalationInstructionsPresent,
    string CommunicationMethod,
    bool CommunicationCompleted,
    bool LocationCallbackReconfirmed,
    bool EmergencyInstructionProvided,
    bool EmergencyHandoffStatusPresent,
    bool ContactAttemptSummaryPresent);

public sealed record TelehealthPharmacyChoicePresenceResponse(
    int Version,
    bool PatientChoiceConfirmed);

public sealed record TelehealthCompletionPrerequisitesResponse(
    Guid ConsultationId,
    string ConsultationStatus,
    string RequestStatus,
    string ShiftStatus,
    string AppointmentStatus,
    DateTimeOffset AsOf,
    TelehealthDocumentationPresenceResponse Documentation,
    TelehealthDispositionPresenceResponse? SafetyDisposition,
    TelehealthPharmacyChoicePresenceResponse? PharmacyChoice,
    bool StructuralEvidencePresent,
    IReadOnlyList<string> ProductBlockers,
    bool SigningEnabled,
    bool CompletionEnabled,
    bool PatientDeliveryEnabled,
    bool DownstreamCreationEnabled,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthPrescriptionCatalogItemResponse(
    string RxNormCode,
    string DrugName,
    string DisplayName,
    string Form,
    string Strength,
    string Route);

public sealed record RecordTelehealthPrescriptionPreparationDraftRequest(
    int ExpectedVersion,
    string RxNormCode,
    decimal DoseAmount,
    string DoseUnit,
    string Frequency,
    decimal QuantityValue,
    string QuantityUnit,
    int DurationDays,
    int Refills,
    string Indication,
    string Directions,
    bool MedicationListReviewed,
    bool AllergyListReviewed,
    bool AdequateEvaluationCompleted,
    bool SyntheticDataConfirmed);

public sealed record TelehealthPrescriptionPreparationDraftResponse(
    int Version,
    string RxNormCode,
    string DrugName,
    string DisplayName,
    string Form,
    string Strength,
    string Route,
    decimal DoseAmount,
    string DoseUnit,
    string Frequency,
    decimal QuantityValue,
    string QuantityUnit,
    int DurationDays,
    int Refills,
    string Indication,
    string Directions,
    bool MedicationListReviewed,
    bool AllergyListReviewed,
    bool AdequateEvaluationCompleted,
    int PharmacyChoiceVersion,
    DateTimeOffset RecordedAt,
    bool LegalEffect,
    bool SafetyChecked,
    bool Signed,
    bool TransmissionQueued,
    bool Transmitted,
    bool PatientDelivered);

public sealed record TelehealthPrescriptionPreparationWorkspaceResponse(
    Guid ConsultationId,
    string ConsultationStatus,
    DateTimeOffset AsOf,
    string CatalogSource,
    string CatalogDatasetId,
    string CatalogDatasetVersion,
    string AdapterMode,
    string CanonicalModelVersion,
    string IntendedStandard,
    int? CurrentPharmacyChoiceVersion,
    IReadOnlyList<TelehealthPrescriptionCatalogItemResponse> CatalogResults,
    TelehealthPrescriptionPreparationDraftResponse? CurrentDraft,
    bool SafetyCheckEnabled,
    bool SigningEnabled,
    bool PrescriptionCreationEnabled,
    bool TransmissionEnabled,
    bool PatientDeliveryEnabled,
    bool CompletionEnabled,
    IReadOnlyList<string> Limitations);

public sealed record AcknowledgeTelehealthApplicantNoticeRequest(
    int ExpectedVersion,
    string NoticeKey,
    int NoticeVersion,
    string CurrentLocationStateCode,
    bool CurrentLocationConfirmed,
    bool ModeOfCareAcknowledged,
    bool PrivacyLimitationsAcknowledged,
    bool EmergencyInstructionsAcknowledged,
    bool InPersonOptionAcknowledged,
    bool ClinicianReconfirmationRequiredAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantNoticeResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string NoticeKey,
    int NoticeVersion,
    string CurrentLocationStateCode,
    string Title,
    string Summary,
    string SourceTitle,
    string SourceUrl,
    IReadOnlyList<string> Disclosures,
    IReadOnlyList<string> DeferredRequirements,
    string PolicyKey,
    int PolicyVersion,
    string LegalReviewStatus,
    bool Acknowledged,
    DateTimeOffset? AcknowledgedAt,
    bool LegalConsentEstablished,
    bool ClinicianConsentDocumented,
    bool ClinicianReconfirmationRequired,
    bool PortalAccountCreated,
    bool IntakeCompleted,
    bool PracticeAccepted,
    bool InsuranceCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantRegistrationDetailsRequest(
    int ExpectedVersion,
    string DetailsFingerprint,
    bool LegalNameAndBirthDateConfirmed,
    bool ContactChannelsConfirmed,
    bool ResidenceRegionConfirmed,
    bool NoCorrectionsNeededConfirmed,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantRegistrationDetailsResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    string DetailsFingerprint,
    string PolicyKey,
    int PolicyVersion,
    bool Confirmed,
    DateTimeOffset? ConfirmedAt,
    bool IdentityAssuranceEstablished,
    bool PatientRecordChanged,
    bool CorrectionCompleted,
    bool IntakeCompleted,
    bool LegalConsentEstablished,
    bool PracticeAccepted,
    bool InsuranceConfirmed,
    bool CoverageCreated,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantInsuranceHandoffRequest(
    int ExpectedVersion,
    string InsuranceSnapshotFingerprint,
    bool PayerAndProductConfirmed,
    bool MaskedMemberDetailsConfirmed,
    bool SubscriberRelationshipConfirmed,
    bool EvidenceLimitationsAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantInsuranceHandoffResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string PayerDisplayName,
    string ProductDisplayName,
    string MemberIdMask,
    string? GroupNumberMask,
    string SubscriberRelationship,
    string CoveragePriority,
    string EligibilityBusinessOutcome,
    DateTimeOffset EligibilityCheckedAt,
    DateTimeOffset EligibilityExpiresAt,
    bool EligibilityEvidenceCurrent,
    string PracticeNetworkBusinessOutcome,
    DateTimeOffset PracticeNetworkCheckedAt,
    DateTimeOffset PracticeNetworkExpiresAt,
    bool PracticeNetworkEvidenceCurrent,
    bool RenderingPhysicianNetworkChecked,
    string InsuranceSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    bool InsuranceDetailsConfirmed,
    DateTimeOffset? ConfirmedAt,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool CanonicalCoverageCreated,
    bool PatientRecordChanged,
    bool PortalAccessEnabled,
    bool IntakeCompleted,
    bool LegalConsentEstablished,
    bool PracticeAccepted,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantCommunicationAccessReadinessRequest(
    int ExpectedVersion,
    string ContextSnapshotFingerprint,
    string PreferredSpokenLanguage,
    bool InterpreterRequested,
    bool AccessibilitySupportRequested,
    bool CurrentLocationConfirmed,
    bool CallbackNumberConfirmed,
    bool SafeAndPrivateToCommunicateConfirmed,
    bool DisconnectionAndEmergencyPlanAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantCommunicationAccessReadinessResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string CurrentLocationStateCode,
    string MaskedCallbackPhone,
    IReadOnlyList<string> SupportedSpokenLanguages,
    string? PreferredSpokenLanguage,
    bool? InterpreterRequested,
    bool? AccessibilitySupportRequested,
    string ContextSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    bool ReadinessRecorded,
    DateTimeOffset? RecordedAt,
    bool SafeAndPrivateToCommunicateConfirmed,
    bool InterpreterAssigned,
    bool AccessibilityAccommodationArranged,
    bool CommunicationArrangementCompleted,
    bool SupportRequestCreated,
    bool TechnologyReadinessCompleted,
    bool PatientRecordChanged,
    bool IntakeCompleted,
    bool LegalConsentEstablished,
    bool PracticeAccepted,
    bool RequestCreated,
    bool QueueEnabled,
    bool CareEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantDevicePreparationRequest(
    int ExpectedVersion,
    string PreparationSnapshotFingerprint,
    bool BrowserSupported,
    bool CameraAvailable,
    bool MicrophoneAvailable,
    bool SpeakerAvailable,
    string NetworkQuality,
    bool ClientReportedResultAcknowledged,
    bool NoReadinessGuaranteeAcknowledged,
    bool RecheckBeforeConsultationAcknowledged);

public sealed record TelehealthApplicantDevicePreparationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    IReadOnlyList<string> SupportedNetworkQualities,
    string PreparationSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    bool PreparationRecorded,
    DateTimeOffset? RecordedAt,
    bool? BrowserSupported,
    bool? CameraAvailable,
    bool? MicrophoneAvailable,
    bool? SpeakerAvailable,
    string? NetworkQuality,
    bool ClientReportedResultAcknowledged,
    bool NoReadinessGuaranteeAcknowledged,
    bool RecheckBeforeConsultationAcknowledged,
    bool TechnologyReady,
    bool WaitingRoomCreated,
    bool MediaSessionCreated,
    bool CommunicationStarted,
    bool SupportArrangementCompleted,
    bool PatientRecordChanged,
    bool IntakeCompleted,
    bool LegalConsentEstablished,
    bool PracticeAccepted,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantClinicalInformationInventoryRequest(
    int ExpectedVersion,
    string InventorySnapshotFingerprint,
    string MedicationsStatus,
    string AllergiesOrIntolerancesStatus,
    string OtherHealthHistoryStatus,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool NoClinicalDetailsCapturedAcknowledged,
    bool ClinicianReconciliationRequiredAcknowledged);

public sealed record TelehealthApplicantClinicalInformationInventoryResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    IReadOnlyList<string> SupportedCategoryStatuses,
    string InventorySnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    bool InventoryRecorded,
    DateTimeOffset? RecordedAt,
    string? MedicationsStatus,
    string? AllergiesOrIntolerancesStatus,
    string? OtherHealthHistoryStatus,
    string? ReviewRoute,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool NoClinicalDetailsCapturedAcknowledged,
    bool ClinicianReconciliationRequiredAcknowledged,
    bool MedicationListReconciled,
    bool AllergyListReconciled,
    bool HealthHistoryReconciled,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool ClinicianReviewCreated,
    bool PatientRecordChanged,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    bool PrescribingEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantMedicationItemRequest(
    string CatalogKey,
    string ReportedUseStatus);

public sealed record RecordTelehealthApplicantMedicationInformationRequest(
    int ExpectedVersion,
    string MedicationInformationSnapshotFingerprint,
    IReadOnlyList<RecordTelehealthApplicantMedicationItemRequest>? MedicationItems,
    bool AdditionalOrUnlistedItemsReported,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool SyntheticCatalogIncompleteAcknowledged,
    bool NoDoseOrDirectionsCapturedAcknowledged,
    bool ClinicianReconciliationRequiredAcknowledged);

public sealed record TelehealthApplicantMedicationItemResponse(
    string CatalogKey,
    string DisplayName,
    int CatalogVersion,
    string CodingSystem,
    bool RxNormMapped,
    string ReportedUseStatus);

public sealed record TelehealthApplicantMedicationInformationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string InventoryMedicationsStatus,
    string MedicationInformationSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    string CatalogKey,
    int CatalogVersion,
    string CodingSystem,
    bool CatalogComplete,
    IReadOnlyList<SyntheticTelehealthApplicantMedicationCatalogItem> CatalogItems,
    IReadOnlyList<string> SupportedReportedUseStatuses,
    bool MedicationInformationRecorded,
    DateTimeOffset? RecordedAt,
    IReadOnlyList<TelehealthApplicantMedicationItemResponse> MedicationItems,
    bool AdditionalOrUnlistedItemsReported,
    string? ReviewRoute,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool SyntheticCatalogIncompleteAcknowledged,
    bool NoDoseOrDirectionsCapturedAcknowledged,
    bool ClinicianReconciliationRequiredAcknowledged,
    bool MedicationStatementCreated,
    bool MedicationRequestCreated,
    bool MedicationListReconciled,
    bool InteractionCheckPerformed,
    bool ClinicianReviewCreated,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool PatientRecordChanged,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    bool PrescribingEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantAllergyItemRequest(string CatalogKey);

public sealed record RecordTelehealthApplicantAllergyInformationRequest(
    int ExpectedVersion,
    string AllergyInformationSnapshotFingerprint,
    IReadOnlyList<RecordTelehealthApplicantAllergyItemRequest>? AllergyItems,
    bool AdditionalOrUnlistedItemsReported,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool SyntheticCatalogIncompleteAcknowledged,
    bool NoReactionOrCriticalityCapturedAcknowledged,
    bool ClinicianVerificationRequiredAcknowledged);

public sealed record TelehealthApplicantAllergyItemResponse(
    string CatalogKey,
    string DisplayName,
    string Category,
    int CatalogVersion,
    string CodingSystem,
    bool SnomedCtMapped,
    bool RxNormMapped);

public sealed record TelehealthApplicantAllergyInformationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string InventoryAllergiesOrIntolerancesStatus,
    string AllergyInformationSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    string CatalogKey,
    int CatalogVersion,
    string CodingSystem,
    bool CatalogComplete,
    IReadOnlyList<SyntheticTelehealthApplicantAllergyCatalogItem> CatalogItems,
    bool AllergyInformationRecorded,
    DateTimeOffset? RecordedAt,
    IReadOnlyList<TelehealthApplicantAllergyItemResponse> AllergyItems,
    bool AdditionalOrUnlistedItemsReported,
    string? ReviewRoute,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool SyntheticCatalogIncompleteAcknowledged,
    bool NoReactionOrCriticalityCapturedAcknowledged,
    bool ClinicianVerificationRequiredAcknowledged,
    bool AllergyIntoleranceCreated,
    bool AllergyListReconciled,
    bool ReactionAssessed,
    bool CriticalityAssessed,
    bool ContraindicationCheckPerformed,
    bool ClinicianReviewCreated,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool PatientRecordChanged,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    bool PrescribingEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record RecordTelehealthApplicantHealthHistoryTopicRequest(string CatalogKey);

public sealed record RecordTelehealthApplicantHealthHistoryInformationRequest(
    int ExpectedVersion,
    string HealthHistoryInformationSnapshotFingerprint,
    IReadOnlyList<RecordTelehealthApplicantHealthHistoryTopicRequest>? HealthHistoryTopics,
    bool AdditionalOrUnlistedTopicsReported,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool TopicSelectionIsNotDiagnosisAcknowledged,
    bool NoStatusOrTimingCapturedAcknowledged,
    bool ClinicianVerificationRequiredAcknowledged);

public sealed record TelehealthApplicantHealthHistoryTopicResponse(
    string CatalogKey,
    string DisplayName,
    string Category,
    int CatalogVersion,
    string CodingSystem,
    bool SnomedCtMapped,
    bool Icd10CmMapped,
    bool LoincMapped);

public sealed record TelehealthApplicantHealthHistoryInformationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string InventoryOtherHealthHistoryStatus,
    string HealthHistoryInformationSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    string CatalogKey,
    int CatalogVersion,
    string CodingSystem,
    bool CatalogComplete,
    IReadOnlyList<SyntheticTelehealthApplicantHealthHistoryTopic> CatalogTopics,
    bool HealthHistoryInformationRecorded,
    DateTimeOffset? RecordedAt,
    IReadOnlyList<TelehealthApplicantHealthHistoryTopicResponse> HealthHistoryTopics,
    bool AdditionalOrUnlistedTopicsReported,
    string? ReviewRoute,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool TopicSelectionIsNotDiagnosisAcknowledged,
    bool NoStatusOrTimingCapturedAcknowledged,
    bool ClinicianVerificationRequiredAcknowledged,
    bool ConditionCreated,
    bool ProcedureCreated,
    bool ObservationCreated,
    bool FamilyMemberHistoryCreated,
    bool QuestionnaireResponseCreated,
    bool HealthHistoryReconciled,
    bool RiskModifierEvaluated,
    bool ClinicalTriageChanged,
    bool ClinicianReviewCreated,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool PatientRecordChanged,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    bool PrescribingEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantClinicalInformationSummaryRequest(
    int ExpectedVersion,
    string ClinicalInformationSummarySnapshotFingerprint,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool NotClinicallyVerifiedOrReconciledAcknowledged,
    bool NoIntakeCompletionOrEligibilityAcknowledged,
    bool CorrectionRequiresSeparateWorkflowAcknowledged);

public sealed record TelehealthApplicantClinicalInformationSummaryCategoryResponse(
    string CategoryKey,
    string InventoryStatus,
    int SelectedItemCount,
    bool AdditionalOrUnlistedItemsReported,
    string ReviewRoute);

public sealed record TelehealthApplicantClinicalInformationSummaryResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string ClinicalInformationSummarySnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    IReadOnlyList<TelehealthApplicantClinicalInformationSummaryCategoryResponse> Categories,
    string SummaryRoute,
    bool SummaryConfirmed,
    DateTimeOffset? ConfirmedAt,
    bool PatientReportedMayBeIncompleteAcknowledged,
    bool NotClinicallyVerifiedOrReconciledAcknowledged,
    bool NoIntakeCompletionOrEligibilityAcknowledged,
    bool CorrectionRequiresSeparateWorkflowAcknowledged,
    bool QuestionnaireResponseCreated,
    bool MedicationListReconciled,
    bool AllergyListReconciled,
    bool HealthHistoryReconciled,
    bool ConfirmedNegativeEstablished,
    bool ClinicianReviewCreated,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool ClinicalTriageChanged,
    bool PatientRecordChanged,
    bool PracticeAccepted,
    bool RequestCreated,
    bool QueueEntered,
    bool CareAuthorized,
    bool PrescribingEnabled,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record AcknowledgeTelehealthApplicantPreRequestReadinessRequest(
    int ExpectedVersion,
    string PreRequestReadinessSnapshotFingerprint,
    bool PriorSectionsReviewedAcknowledged,
    bool OutstandingStepsRemainAcknowledged,
    bool NoRequestOrQueueCreatedAcknowledged,
    bool CorrectionRequiresSeparateWorkflowAcknowledged);

public sealed record TelehealthApplicantPreRequestReadinessSectionResponse(
    string SectionKey,
    string ReceiptState,
    string OutstandingRoute);

public sealed record TelehealthApplicantPreRequestReadinessResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string PreRequestReadinessSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    IReadOnlyList<TelehealthApplicantPreRequestReadinessSectionResponse> Sections,
    string OverallRoute,
    bool ReadinessAcknowledged,
    DateTimeOffset? AcknowledgedAt,
    bool PriorSectionsReviewedAcknowledged,
    bool OutstandingStepsRemainAcknowledged,
    bool NoRequestOrQueueCreatedAcknowledged,
    bool CorrectionRequiresSeparateWorkflowAcknowledged,
    bool IdentityAssuranceEstablished,
    bool CoverageGuaranteed,
    bool RenderingClinicianNetworkVerified,
    bool InterpreterOrAccommodationArranged,
    bool TechnologyReady,
    bool ClinicalInformationReconciled,
    bool ClinicalIntakeCompleted,
    bool ClinicalEligibilityEstablished,
    bool LegalConsentEstablished,
    bool StaffReviewCreated,
    bool ClinicianReviewCreated,
    bool PracticeAccepted,
    bool PatientRecordChanged,
    bool RequestCreated,
    bool QueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record SubmitTelehealthApplicantPracticeReviewRequest(
    int ExpectedVersion,
    string PracticeReviewSnapshotFingerprint,
    bool PatientReportedInformationAcknowledged,
    bool PracticeMayRequestInformationOrDeclineAcknowledged,
    bool NoTelehealthRequestOrCareQueueAcknowledged,
    bool WorseningSymptomsRequireImmediateActionAcknowledged);

public sealed record TelehealthApplicantPracticeReviewResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string PracticeReviewSnapshotFingerprint,
    string PolicyKey,
    int PolicyVersion,
    string ReviewRoute,
    bool SubmissionReady,
    bool Submitted,
    Guid? PracticeReviewCaseId,
    string? ReviewStatus,
    DateTimeOffset? SubmittedAt,
    bool PatientReportedInformationAcknowledged,
    bool PracticeMayRequestInformationOrDeclineAcknowledged,
    bool NoTelehealthRequestOrCareQueueAcknowledged,
    bool WorseningSymptomsRequireImmediateActionAcknowledged,
    bool StaffReviewCreated,
    bool ClinicianReviewCreated,
    bool PracticeAccepted,
    bool PatientRecordChanged,
    bool TelehealthRequestCreated,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record CreateTelehealthApplicantRequest(
    int ExpectedApplicantVersion,
    int AuthorizationPolicyVersion,
    bool RequestCreationConfirmed,
    bool NoQueueOrCareAcknowledged,
    bool UrgentOrWorseningSymptomsRequireImmediateActionAcknowledged);

public sealed record TelehealthApplicantRequestCreationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    string PolicyKey,
    int PolicyVersion,
    int AuthorizationPolicyVersion,
    bool RequestCreationReady,
    bool RequestCreated,
    Guid? RequestId,
    string? RequestStatus,
    int? RequestVersion,
    string ComplaintCategory,
    DateTimeOffset? CreatedAt,
    bool TelehealthRequestCreated,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantRequestLocation(
    int ExpectedRequestVersion,
    string ContextSnapshotFingerprint,
    string CurrentLocationStateCode,
    bool CurrentLocationConfirmed,
    bool CallbackNumberConfirmed,
    bool ChangedLocationRequiresRestartAcknowledged,
    bool UrgentOrWorseningSymptomsRequireImmediateActionAcknowledged);

public sealed record TelehealthApplicantRequestLocationResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string PolicyKey,
    int PolicyVersion,
    string ContextSnapshotFingerprint,
    string CurrentLocationStateCode,
    string MaskedCallbackPhone,
    bool ConfirmationReady,
    bool LocationConfirmed,
    DateTimeOffset? ConfirmedAt,
    bool TriageAssessmentCreated,
    bool ClinicalReviewCreated,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record EvaluateTelehealthApplicantRequestUniversalSafety(
    int ExpectedRequestVersion,
    string ContextSnapshotFingerprint,
    string CurrentLocationStateCode,
    bool CurrentLocationConfirmed,
    bool CallbackNumberConfirmed,
    bool SyntheticDataConfirmed,
    bool? HasEmergencyWarning,
    bool? SevereOrWorsening,
    bool? RequiresHandsOnExam,
    bool? Unsure);

public sealed record TelehealthApplicantRequestUniversalSafetyResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string PolicyKey,
    int PolicyVersion,
    string ProtocolKey,
    int ProtocolVersion,
    string ContextSnapshotFingerprint,
    DateTimeOffset ContextExpiresAt,
    string CurrentLocationStateCode,
    string MaskedCallbackPhone,
    bool AssessmentReady,
    bool AssessmentCreated,
    string? Outcome,
    string? PublicDisposition,
    DateTimeOffset? EvaluatedAt,
    bool UniversalSafetyPassed,
    bool ComplaintSpecificTriageRequired,
    bool ComplaintSpecificTriageCreated,
    bool ClinicalReviewRequired,
    bool ClinicalReviewCreated,
    bool TerminalForTelehealth,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthSyntheticMigraineComplaintTriageAnswers(
    string? SuddenOrWorstOnset,
    string? NewNeurologicOrVisionChange,
    string? FeverOrStiffNeck,
    string? RecentHeadInjury,
    string? PregnantOrPostpartum,
    string? CancerOrImmunocompromised,
    string? KnownSimilarPattern,
    string? PersistentVomiting);

public sealed record TelehealthSyntheticSleepComplaintTriageAnswers(
    string? SelfHarmThoughts,
    string? ManiaOrPsychosis,
    string? DangerousSomnolence,
    string? WithdrawalConcern,
    string? BreathingPausesOrSevereSnoring,
    string? PregnantOrComplexMedicationConcern,
    string? ControlledSedativeRequest,
    string? UncomplicatedSleepDifficulty);

public sealed record EvaluateTelehealthApplicantRequestComplaintTriage(
    int ExpectedRequestVersion,
    string ContextSnapshotFingerprint,
    string CurrentLocationStateCode,
    bool CurrentLocationConfirmed,
    bool CallbackNumberConfirmed,
    bool SyntheticDataConfirmed,
    TelehealthSyntheticMigraineComplaintTriageAnswers? Migraine,
    TelehealthSyntheticSleepComplaintTriageAnswers? Sleep);

public sealed record TelehealthApplicantRequestComplaintTriageResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string ComplaintCategory,
    string PolicyKey,
    int PolicyVersion,
    string ProtocolKey,
    int ProtocolVersion,
    string EngineVersion,
    string ClinicalContentStatus,
    bool MedicalDirectorApprovalRequired,
    bool MedicalDirectorApprovalRecorded,
    bool ClinicalGoldenCasePackApproved,
    bool ProductionPublicationAllowed,
    string ContextSnapshotFingerprint,
    DateTimeOffset ContextExpiresAt,
    string CurrentLocationStateCode,
    string MaskedCallbackPhone,
    bool AssessmentReady,
    bool AssessmentCreated,
    string? Outcome,
    string? PublicDisposition,
    DateTimeOffset? EvaluatedAt,
    bool SyntheticVideoEvaluationCandidate,
    bool ClinicalReviewRequired,
    bool ClinicalReviewCreated,
    bool TerminalForTelehealth,
    bool IntakeSnapshotCreated,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantRequestIntake(
    int ExpectedRequestVersion,
    string ContextSnapshotFingerprint,
    string CurrentLocationStateCode,
    string SymptomDuration,
    bool CurrentLocationConfirmed,
    bool CallbackNumberConfirmed,
    bool PriorInformationReviewed,
    bool InsuranceLimitationsAcknowledged,
    bool PendingConsentAcknowledged,
    bool PendingVerificationAcknowledged,
    bool ComplaintResultAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantRequestIntakeSectionResponse(
    string SectionKey,
    string ReceiptState,
    string OutstandingRoute);

public sealed record TelehealthApplicantRequestIntakeResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string ComplaintCategory,
    string ComplaintDisplayLabel,
    string PolicyKey,
    int PolicyVersion,
    string ClinicalContentStatus,
    bool MedicalDirectorApprovalRequired,
    bool MedicalDirectorApprovalRecorded,
    bool ClinicalGoldenCasePackApproved,
    bool ProductionPublicationAllowed,
    string ContextSnapshotFingerprint,
    DateTimeOffset ContextExpiresAt,
    string CurrentLocationStateCode,
    string MaskedCallbackPhone,
    IReadOnlyList<string> SupportedSymptomDurations,
    IReadOnlyList<TelehealthApplicantRequestIntakeSectionResponse> Sections,
    bool SnapshotReady,
    bool SnapshotCreated,
    string? SymptomDuration,
    DateTimeOffset? CapturedAt,
    bool VerificationPending,
    bool ConsentPending,
    bool CoverageRecordCreated,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool OperationalReviewCreated,
    bool PracticeAccepted,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record ConfirmTelehealthApplicantRequestInsuranceSource(
    int ExpectedRequestVersion,
    string InsuranceSourceSnapshotFingerprint,
    bool PayerProductConfirmed,
    bool MaskedMemberDetailsConfirmed,
    bool SubscriberRelationshipConfirmed,
    bool PrimaryCoverageSourceConfirmed,
    bool FreshVerificationRequested,
    bool EvidenceLimitationsAcknowledged,
    bool SyntheticDataConfirmed);

public sealed record TelehealthApplicantRequestInsuranceSourceResponse(
    Guid ApplicantId,
    int ApplicantVersion,
    string ApplicantStatus,
    Guid RequestId,
    int RequestVersion,
    string RequestStatus,
    string PolicyKey,
    int PolicyVersion,
    string InsuranceSourceSnapshotFingerprint,
    DateTimeOffset ContextExpiresAt,
    string PayerDisplayName,
    string ProductDisplayName,
    string MaskedMemberId,
    string? MaskedGroupNumber,
    string SubscriberRelationship,
    string CoveragePriority,
    string PreviousEligibilityBusinessOutcome,
    DateTimeOffset PreviousEligibilityCheckedAt,
    DateTimeOffset PreviousEligibilityExpiresAt,
    bool PreviousEligibilityEvidenceExpired,
    string PreviousPracticeNetworkBusinessOutcome,
    DateTimeOffset PreviousPracticeNetworkCheckedAt,
    DateTimeOffset PreviousPracticeNetworkExpiresAt,
    bool PreviousPracticeNetworkEvidenceExpired,
    bool PreviousRenderingPhysicianNetworkChecked,
    bool PreviousResultReusable,
    bool SourceReady,
    bool SourceConfirmed,
    DateTimeOffset? ConfirmedAt,
    bool ProtectedPayloadReferenced,
    bool ProtectedPayloadCopied,
    bool ProtectedPayloadDecrypted,
    bool FreshVerificationRequested,
    bool CanonicalCoverageCreated,
    bool CoverageSelected,
    bool EligibilityVerificationCreated,
    bool NetworkVerificationCreated,
    bool RenderingPhysicianNetworkChecked,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool FinancialRouteCreated,
    bool OperationalReviewCreated,
    bool PracticeAccepted,
    bool PatientContacted,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool DoctorSearchStarted,
    bool QueuePositionAssigned,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    string Direction,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthApplicantPracticeReviewInboxSectionResponse(
    string SectionKey,
    string ReceiptState,
    string OutstandingRoute);

public sealed record TelehealthApplicantPracticeReviewInboxItemResponse(
    Guid PracticeReviewCaseId,
    int ApplicantVersion,
    string ApplicantStatus,
    string ReviewStatus,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    string PurposeCategory,
    string PurposeDisplayLabel,
    string SafetyOutcome,
    string ReviewRoute,
    IReadOnlyList<TelehealthApplicantPracticeReviewInboxSectionResponse> Sections,
    DateTimeOffset SubmittedAt,
    bool StaffReviewWorkItemExists,
    bool StaffActionTaken,
    bool Assigned,
    bool AssignedToCurrentUser,
    DateTimeOffset? AssignmentExpiresAt,
    bool PriorityAssigned,
    bool PracticeAccepted,
    bool PracticeDeclined,
    bool PatientContacted,
    bool ClinicianReviewCreated,
    bool TelehealthRequestCreated,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed);

public sealed record TelehealthApplicantPracticeReviewInboxResponse(
    string PolicyKey,
    int PolicyVersion,
    string PracticeDisplayName,
    DateTimeOffset ServerTime,
    IReadOnlyList<TelehealthApplicantPracticeReviewInboxItemResponse> Items,
    IReadOnlyList<string> Limitations);

public sealed record ClaimTelehealthApplicantPracticeReviewRequest(
    int ExpectedApplicantVersion,
    int InboxPolicyVersion,
    bool NoDecisionAcknowledged,
    bool NoPatientContactAcknowledged,
    bool NoRequestOrCareQueueAcknowledged);

public sealed record TelehealthApplicantPracticeReviewClaimResponse(
    Guid ClaimId,
    Guid PracticeReviewCaseId,
    int ApplicantVersion,
    string PolicyKey,
    int PolicyVersion,
    string EvidenceType,
    DateTimeOffset AssignedAt,
    DateTimeOffset AssignmentExpiresAt,
    bool Assigned,
    bool AssignedToCurrentUser,
    bool StaffReviewWorkItemExists,
    bool StaffActionTaken,
    bool PriorityAssigned,
    bool PracticeAccepted,
    bool PracticeDeclined,
    bool PatientContacted,
    bool ClinicianReviewCreated,
    bool TelehealthRequestCreated,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    IReadOnlyList<string> Limitations);

public sealed record TelehealthApplicantPracticeReviewPacketRegistrationResponse(
    bool ReceiptRecorded,
    DateTimeOffset ConfirmedAt,
    bool IdentityAssuranceEstablished,
    bool PatientRecordChanged);

public sealed record TelehealthApplicantPracticeReviewPacketInsuranceResponse(
    string PayerDisplayName,
    string ProductDisplayName,
    string MemberIdMask,
    string? GroupNumberMask,
    string SubscriberRelationship,
    string CoveragePriority,
    string EligibilityBusinessOutcome,
    DateTimeOffset EligibilityCheckedAt,
    DateTimeOffset EligibilityExpiresAt,
    bool EligibilityEvidenceCurrent,
    string PracticeNetworkBusinessOutcome,
    DateTimeOffset PracticeNetworkCheckedAt,
    DateTimeOffset PracticeNetworkExpiresAt,
    bool PracticeNetworkEvidenceCurrent,
    bool RenderingPhysicianNetworkChecked,
    DateTimeOffset ConfirmedAt,
    bool CoverageVerified,
    bool ExactNetworkConfirmed,
    bool CanonicalCoverageCreated);

public sealed record TelehealthApplicantPracticeReviewPacketCommunicationResponse(
    string PreferredSpokenLanguage,
    bool InterpreterRequested,
    bool AccessibilitySupportRequested,
    bool SafePrivateCommunicationConfirmed,
    DateTimeOffset RecordedAt,
    bool InterpreterAssigned,
    bool AccessibilityAccommodationArranged,
    bool CommunicationArrangementCompleted);

public sealed record TelehealthApplicantPracticeReviewPacketDeviceResponse(
    bool BrowserSupported,
    bool CameraAvailable,
    bool MicrophoneAvailable,
    bool SpeakerAvailable,
    string NetworkQuality,
    DateTimeOffset RecordedAt,
    bool TechnologyReady,
    bool WaitingRoomCreated,
    bool MediaSessionCreated);

public sealed record TelehealthApplicantPracticeReviewPacketResponse(
    Guid PracticeReviewCaseId,
    int ApplicantVersion,
    string ApplicantStatus,
    string ReviewStatus,
    string PolicyKey,
    int PolicyVersion,
    string PracticeDisplayName,
    DateTimeOffset ServerTime,
    DateTimeOffset AssignmentExpiresAt,
    string LegalFirstName,
    string LegalLastName,
    DateOnly DateOfBirth,
    string MaskedEmail,
    string MaskedPhone,
    string ResidenceStateCode,
    string PostalCode,
    string PurposeCategory,
    string PurposeDisplayLabel,
    string SafetyOutcome,
    string ReviewRoute,
    DateTimeOffset SubmittedAt,
    IReadOnlyList<TelehealthApplicantPracticeReviewInboxSectionResponse> Sections,
    TelehealthApplicantPracticeReviewPacketRegistrationResponse Registration,
    TelehealthApplicantPracticeReviewPacketInsuranceResponse Insurance,
    TelehealthApplicantPracticeReviewPacketCommunicationResponse CommunicationAccess,
    TelehealthApplicantPracticeReviewPacketDeviceResponse DevicePreparation,
    string ClinicalInformationSummaryRoute,
    DateTimeOffset ClinicalInformationSummaryConfirmedAt,
    bool StaffReviewWorkItemExists,
    bool StaffActionTaken,
    bool Assigned,
    bool AssignedToCurrentUser,
    bool PriorityAssigned,
    bool PracticeAccepted,
    bool PracticeDeclined,
    bool PatientContacted,
    bool ClinicianReviewCreated,
    bool TelehealthRequestCreated,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    IReadOnlyList<string> Limitations);

public sealed record AuthorizeTelehealthApplicantPracticeReviewRequest(
    int ExpectedApplicantVersion,
    int PacketPolicyVersion,
    string Decision,
    string RationaleCode,
    bool NoClinicalEligibilityAcknowledged,
    bool NoCoverageGuaranteeAcknowledged,
    bool NoRequestOrQueueAcknowledged);

public sealed record TelehealthApplicantPracticeReviewAuthorizationResponse(
    Guid PracticeReviewCaseId,
    int ApplicantVersion,
    string ApplicantStatus,
    string Decision,
    string RationaleCode,
    string PolicyKey,
    int PolicyVersion,
    string EvidenceType,
    DateTimeOffset DecidedAt,
    bool RequestCreationAuthorized,
    bool PracticeAccepted,
    bool PatientContacted,
    bool ClinicianReviewCreated,
    bool TelehealthRequestCreated,
    bool PatientCareQueueEntered,
    bool ClinicianQueueEntered,
    bool AppointmentCreated,
    bool EncounterCreated,
    bool ConsentCreated,
    bool CareAuthorized,
    bool PrescribingEnabled,
    bool BillingEnabled,
    bool ClaimCreated,
    bool IntegrationEnabled,
    bool ExternalCallPerformed,
    IReadOnlyList<string> Limitations);

public sealed record SyntheticTelehealthTriageAnswers(
    bool HasEmergencyWarning,
    bool SevereOrWorsening,
    bool RequiresHandsOnExam,
    bool Unsure);

public sealed record TelehealthTriageResult(
    Guid ProtocolId,
    string ProtocolKey,
    int ProtocolVersion,
    string ProtocolContentHash,
    TelehealthTriageOutcome Outcome,
    string AnswerFingerprint);

public sealed record TelehealthCoverageGatewayInput(
    string PracticeId,
    int FacilityId,
    Guid RequestId,
    string PatientId,
    string StateCode,
    string ComplaintCategory,
    string RequestStatus,
    string CoverageRecordId,
    string CoverageType,
    string Provider,
    string PlanName,
    string CoverageFingerprint);

public sealed record TelehealthCoverageGatewayResult(
    string AdapterMode,
    TelehealthEligibilityStatus EligibilityStatus,
    TelehealthNetworkStatus NetworkStatus,
    TelehealthFinancialRoute FinancialRoute,
    string EligibilitySource,
    string NetworkSource,
    string EvidenceKey,
    int EvidenceVersion,
    string InputFingerprint,
    IReadOnlyList<string> Limitations);
